---
settings:
  name: Release Notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Notes de version BlueXP
    url: "/index.html"
  - title: Modifications récentes
    url: "/whats-new.html"
  - title: Index BlueXP
    url: "/release-notes-index.html"
homepage:
  tiles:
  - title: Quoi de neuf
    links:
    - title: Changements récents dans BlueXP
      url: whats-new.html
  - title: Notes de version par service
    links:
    - title: Index des notes de version
      url: release-notes-index.html
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog du site Web BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
