---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: Découvrez les derniers changements apportés aux services Cloud intégrés à la plateforme BlueXP. 
---
= Changements récents dans BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les derniers changements apportés aux services Cloud intégrés à la plateforme BlueXP. Pour consulter l'historique complet des versions, accédez au link:release-notes-index.html["ensemble complet de notes de version"] pour chaque service.



== Fonctionnalités administratives

Cette section décrit les nouvelles fonctionnalités liées aux fonctions d'administration de BlueXP : comptes, connecteurs, informations d'identification du fournisseur cloud, etc.



=== 31 juillet 2025



==== Version du mode privé (3.9.54)

Une nouvelle version en mode privé est désormais disponible au téléchargement sur le https://mysupport.netapp.com/site/downloads["Site de support NetApp"^]

La version 3.9.54 inclut des mises à jour des composants et services BlueXP suivants.

[cols="3*"]
|===
| Composant ou service | Version incluse dans cette version | Modifications depuis la version précédente du mode privé 


| Connecteur | 3.9.54, 3.9.53 | Aller à la https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Quoi de neuf dans la page BlueXP"^] et reportez-vous aux modifications incluses pour les versions 3.9.54 et 3.9.53. 


| Sauvegarde et restauration | 28 juillet 2025 | Aller à la https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Nouveautés de la page sauvegarde et restauration BlueXP"^] et se référer aux modifications incluses dans la version de juillet 2025. 


| Classement | 14 juillet 2025 (version 1.45) | Aller à la https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Nouveautés de la page de classification BlueXP"^] . 
|===
Pour plus d'informations sur le mode privé, notamment sur la mise à niveau, reportez-vous aux sections suivantes :

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["En savoir plus sur le mode privé"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Découvrez comment démarrer avec BlueXP en mode privé"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Apprenez à mettre à niveau le connecteur lorsque vous utilisez le mode privé"]




=== 21 juillet 2025



==== Prise en charge des Google Cloud NetApp Volumes

Vous pouvez désormais afficher les Google Cloud NetApp Volumes dans BlueXP.link:https://docs.netapp.com/us-en//bluexp-google-cloud-netapp-volumes/index.html["En savoir plus sur Google Cloud NetApp Volumes."]



==== Gestion des identités et des accès BlueXP



===== Nouveau rôle d'accès pour Google Cloud NetApp Volumes

BlueXP prend désormais en charge l'utilisation d'un rôle d'accès pour le système de stockage suivant :

* Google Cloud NetApp volumes


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur l’utilisation des rôles d’accès."]



=== 14 juillet 2025



==== Connecteur 3.9.54

Cette version du connecteur BlueXP inclut des améliorations de sécurité, des corrections de bogues et les nouvelles fonctionnalités suivantes :

* Prise en charge des proxys transparents pour les connecteurs dédiés à la prise en charge des services Cloud Volumes ONTAP . link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["En savoir plus sur la configuration d’un proxy transparent."]
* Possibilité d'utiliser des balises réseau pour aider à acheminer le trafic du connecteur lorsque le connecteur est déployé dans un environnement Google Cloud.
* Notifications supplémentaires intégrées au produit pour la surveillance de l'état du connecteur, y compris l'utilisation du processeur et de la RAM.


À l'heure actuelle, la version 3.9.54 est disponible pour le mode standard et le mode restreint.



==== Gestion des identités et des accès BlueXP

La gestion des identités et des accès dans BlueXP offre désormais les fonctionnalités suivantes :

* Prise en charge d'IAM en mode privé, vous permettant de gérer l'accès et les autorisations des utilisateurs pour les services et applications BlueXP .
* Gestion simplifiée des fédérations d'identité, incluant une navigation plus facile, des options plus claires pour la configuration des connexions fédérées et une visibilité améliorée sur les fédérations existantes.
* Rôles d'accès pour la BlueXP backup and recovery, la BlueXP disaster recovery et la gestion de la fédération.




===== Prise en charge d'IAM en mode privé

BlueXP prend désormais en charge l'IAM en mode privé, ce qui vous permet de gérer l'accès et les autorisations des utilisateurs pour les services et applications BlueXP . Cette amélioration permet aux clients en mode privé de tirer parti du contrôle d'accès basé sur les rôles (RBAC) pour une sécurité et une conformité accrues.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["En savoir plus sur IAM dans BlueXP."]



===== Gestion simplifiée des fédérations d'identité

BlueXP propose désormais une interface plus intuitive pour la gestion de la fédération d'identités. Celle-ci comprend une navigation simplifiée, des options plus claires pour la configuration des connexions fédérées et une meilleure visibilité sur les fédérations existantes.

L'activation de l'authentification unique (SSO) via la fédération d'identités permet aux utilisateurs de se connecter à BlueXP avec leurs identifiants d'entreprise. Cela améliore la sécurité, réduit l'utilisation des mots de passe et simplifie l'intégration.

Vous serez invité à importer vos connexions fédérées existantes dans la nouvelle interface pour accéder aux nouvelles fonctionnalités de gestion. Vous pourrez ainsi profiter des dernières améliorations sans avoir à recréer vos connexions fédérées. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["En savoir plus sur l’importation de votre connexion fédérée existante vers BlueXP."]

Une gestion améliorée de la fédération vous permet de :

* Ajoutez plusieurs domaines vérifiés à une connexion fédérée, ce qui vous permet d'utiliser plusieurs domaines avec le même fournisseur d'identité (IdP).
* Désactivez ou supprimez les connexions fédérées lorsque cela est nécessaire, ce qui vous donne le contrôle de l'accès et de la sécurité des utilisateurs.
* Contrôlez l’accès à la gestion de la fédération avec les rôles IAM.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["En savoir plus sur la fédération d’identité dans BlueXP."]



===== Nouveaux rôles d'accès pour la BlueXP backup and recovery, la BlueXP disaster recovery et la gestion de la fédération

BlueXP prend désormais en charge l'utilisation des rôles IAM pour les fonctionnalités et services de données suivants :

* Sauvegarde et restauration BlueXP
* Reprise d'activité BlueXP
* Fédération


link:https://docs.netapp.com/us-en/bluexp-admin/reference-iam-predefined-roles.html["En savoir plus sur l’utilisation des rôles d’accès."]



=== 9 juin 2025



==== Connecteur 3.9.53

Cette version du connecteur BlueXP inclut des améliorations de sécurité et des corrections de bogues.

La version 3.9.53 est disponible pour le mode standard et le mode restreint.



==== Alertes d'utilisation de l'espace disque

Le centre de notifications inclut désormais des alertes sur l’utilisation de l’espace disque sur le connecteur. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["En savoir plus ."^]



==== Améliorations de l'audit

La chronologie inclut désormais les événements de connexion et de déconnexion des utilisateurs. Vous pouvez consulter les activités de connexion, ce qui facilite l'audit et la surveillance de la sécurité. Les utilisateurs de l'API disposant du rôle d'administrateur d'organisation peuvent consulter l'adresse e-mail de l'utilisateur connecté en incluant l'adresse e-mail.  `includeUserData=true`` paramètre comme dans ce qui suit :  `/audit/<account_id>?includeUserData=true` .



==== Gestion des abonnements Keystone disponible dans BlueXP

Vous pouvez gérer votre abonnement NetApp Keystone depuis BlueXP.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Découvrez la gestion des abonnements Keystone dans BlueXP."^]



==== Gestion des identités et des accès BlueXP



===== Authentification multifacteur (MFA)

Les utilisateurs non fédérés peuvent activer l'authentification multifacteur (MFA) pour leurs comptes BlueXP afin d'améliorer la sécurité. Les administrateurs peuvent gérer les paramètres de l'authentification multifacteur, notamment la réinitialisation ou la désactivation de l'authentification multifacteur pour les utilisateurs, selon les besoins. Ceci est pris en charge uniquement en mode standard.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["Découvrez comment configurer l’authentification multifacteur pour vous-même."^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["Découvrez comment administrer l’authentification multifacteur pour les utilisateurs."^]



==== Charges de travail

Vous pouvez désormais afficher et supprimer les informations d’identification Amazon FSx for NetApp ONTAP à partir de la page Informations d’identification dans BlueXP.



== Alertes



=== 7 octobre 2024



==== Page de liste des alertes BlueXP

Vous pouvez rapidement identifier les clusters ONTAP dont la capacité est faible ou les performances sont faibles, évaluer l'étendue de la disponibilité et identifier les risques de sécurité. Vous pouvez afficher les alertes relatives à la capacité, aux performances, à la protection, à la disponibilité, à la sécurité et à la configuration.



==== Détails des alertes

Vous pouvez explorer les détails des alertes et trouver des recommandations.



==== Afficher les détails du cluster liés à ONTAP System Manager

Avec les alertes BlueXP , vous pouvez consulter les alertes associées à votre environnement de stockage ONTAP et explorer les détails liés à ONTAP System Manager.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["En savoir plus sur les alertes BlueXP"].



== Amazon FSX pour ONTAP



=== 03 août 2025



==== Améliorations apportées à l'onglet Relations de réplication

Nous avons ajouté plusieurs nouvelles colonnes au tableau des relations de réplication pour vous donner plus d'informations sur vos relations de réplication dans l'onglet *Relations de réplication*. Le tableau comprend désormais les colonnes suivantes :

* Politique SnapMirror
* Système de fichiers source
* Système de fichiers cible
* État de la relation
* Heure du dernier transfert




=== 14 juillet 2025



==== Prise en charge de la réplication des données entre deux systèmes de fichiers FSx for ONTAP

La réplication des données est désormais disponible entre deux systèmes de fichiers FSx for ONTAP à partir du canevas de la console BlueXP .

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["Réplication des données"]



=== 29 juin 2025



==== Mise à jour des informations d'identification

Après avoir configuré les informations d'identification et les autorisations pour votre système de fichiers FSx for ONTAP, vous serez redirigé vers la page « Informations d'identification BlueXP ». Depuis cette page, vous pouvez renommer ou supprimer vos informations d'identification FSx for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["Configurer les autorisations pour les systèmes de fichiers FSx pour ONTAP"]



== Le stockage Amazon S3



=== 5 mars 2023



==== Possibilité d'ajouter de nouveaux compartiments à partir de BlueXP

Vous avez depuis longtemps la possibilité d'afficher les compartiments Amazon S3 sur BlueXP Canvas. Vous pouvez désormais ajouter de nouveaux compartiments et modifier les propriétés des compartiments existants directement à partir de BlueXP . https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["Découvrez comment ajouter de nouveaux compartiments Amazon S3"].



== Stockage Azure Blob



=== 5 juin 2023



==== Possibilité d'ajouter de nouveaux comptes de stockage à partir de BlueXP

Vous avez pu afficher Azure Blob Storage sur BlueXP Canvas pendant un certain temps. Vous pouvez désormais ajouter de nouveaux comptes de stockage et modifier les propriétés des comptes de stockage existants directement à partir de BlueXP . https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Découvrez comment ajouter de nouveaux comptes de stockage Azure Blob"].



== Azure NetApp Files



=== 13 janvier 2025



==== Fonctionnalités réseau désormais prises en charge dans BlueXP

Lors de la configuration d'un volume dans Azure NetApp Files à partir de BlueXP , vous pouvez maintenant indiquer les fonctionnalités réseau. Cette configuration s'aligne sur la fonctionnalité disponible dans Azure NetApp Files natif.



=== 12 juin 2024



==== Nouvelle autorisation requise

L'autorisation suivante est désormais requise pour gérer les volumes Azure NetApp Files à partir de BlueXP :

Microsoft.Network/virtualNetworks/subnets/read

Cette autorisation est requise pour lire un sous-réseau de réseau virtuel.

Si vous gérez actuellement Azure NetApp Files à partir de BlueXP, vous devez ajouter cette autorisation au rôle personnalisé associé à l'application Microsoft Entra que vous avez créée précédemment.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Découvrez comment configurer une application Microsoft Entra et afficher les autorisations de rôle personnalisées"].



=== 22 avril 2024



==== Les modèles de volume ne sont plus pris en charge

Vous ne pouvez plus créer de volume à partir d'un modèle. Cette action a été associée au service de correction BlueXP, qui n'est plus disponible.



== Sauvegarde et restauration



=== 28 juillet 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



==== Prise en charge des charges de travail Kubernetes en tant qu'aperçu

Cette version de la BlueXP backup and recovery introduit la prise en charge de la découverte et de la gestion des charges de travail Kubernetes :

* Découvrez Red Hat OpenShift et les clusters Kubernetes open source, soutenus par NetApp ONTAP, sans partager les fichiers kubeconfig.
* Découvrez, gérez et protégez les applications sur plusieurs clusters Kubernetes à l’aide d’un plan de contrôle unifié.
* Déchargez les opérations de déplacement de données pour la sauvegarde et la récupération des applications Kubernetes vers NetApp ONTAP.
* Orchestrez les sauvegardes d'applications locales et basées sur le stockage d'objets.
* Sauvegardez et restaurez des applications entières et des ressources individuelles sur n'importe quel cluster Kubernetes.
* Travaillez avec des conteneurs et des machines virtuelles exécutés sur Kubernetes.
* Créez des sauvegardes cohérentes avec les applications à l’aide de hooks d’exécution et de modèles.


Pour plus de détails sur la protection des charges de travail Kubernetes, reportez-vous à  https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-kubernetes-protect-overview.html["Présentation de la protection des charges de travail Kubernetes"] .



=== 14 juillet 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



==== Tableau de bord de volume ONTAP amélioré

En avril 2025, nous avons lancé un aperçu d'un tableau de bord de volume ONTAP amélioré, beaucoup plus rapide et plus efficace.

Ce tableau de bord a été conçu pour aider les entreprises clientes avec un volume de travail important. Même pour les clients avec 20 000 volumes, le nouveau tableau de bord se charge en moins de 10 secondes.

Après une préversion réussie et de très bons retours de la part de nos clients, nous en faisons désormais l'expérience par défaut pour tous nos clients. Préparez-vous à découvrir un tableau de bord ultra-rapide.

Pour plus de détails, voir link:br-use-dashboard.html["Afficher l'état de la protection dans le tableau de bord"].



==== Prise en charge de la charge de travail Microsoft SQL Server en tant qu'aperçu technologique public

Cette version de BlueXP backup and recovery propose une interface utilisateur mise à jour qui vous permet de gérer les charges de travail Microsoft SQL Server grâce à une stratégie de protection 3-2-1, familière au service de BlueXP backup and recovery . Avec cette nouvelle version, vous pouvez sauvegarder ces charges de travail sur le stockage principal, les répliquer sur le stockage secondaire et les sauvegarder sur le stockage objet cloud.

Vous pouvez vous inscrire à l'aperçu en remplissant ce formulaire  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["Aperçu du formulaire d'inscription"^] .


NOTE: Cette documentation sur la protection des charges de travail Microsoft SQL Server est fournie en avant-première technologique. NetApp se réserve le droit de modifier les détails, le contenu et le calendrier de cette offre avant sa disponibilité générale.

Cette version de BlueXP backup and recovery inclut les mises à jour suivantes :

* *Fonctionnalité de sauvegarde 3-2-1* : cette version intègre les fonctionnalités de SnapCenter , vous permettant de gérer et de protéger vos ressources SnapCenter avec une stratégie de protection des données 3-2-1 à partir de l'interface utilisateur de BlueXP backup and recovery .
* *Importer depuis SnapCenter* : Vous pouvez importer les données et les politiques de sauvegarde de SnapCenter dans la BlueXP backup and recovery.
* *Une interface utilisateur repensée* offre une expérience plus intuitive pour la gestion de vos tâches de sauvegarde et de récupération.
* *Cibles de sauvegarde* : vous pouvez ajouter des buckets dans les environnements Amazon Web Services (AWS), Microsoft Azure Blob Storage, StorageGRID et ONTAP S3 à utiliser comme cibles de sauvegarde pour vos charges de travail Microsoft SQL Server.
* *Prise en charge des charges de travail* : Cette version vous permet de sauvegarder, restaurer, vérifier et cloner des bases de données et des groupes de disponibilité Microsoft SQL Server. (La prise en charge d'autres charges de travail sera ajoutée dans les prochaines versions.)
* *Options de restauration flexibles* : Cette version vous permet de restaurer les bases de données vers les emplacements d'origine et alternatifs en cas de corruption ou de perte accidentelle de données.
* *Copies de production instantanées* : générez des copies de production peu encombrantes pour le développement, les tests ou les analyses en quelques minutes au lieu de plusieurs heures ou jours.
* Cette version inclut la possibilité de créer des rapports détaillés.


Pour plus de détails sur la protection des charges de travail Microsoft SQL Server, consultez link:br-use-mssql-protect-overview.html["Présentation de la protection des charges de travail Microsoft SQL Server"] .



=== 09 juin 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



==== Mises à jour du support du catalogue indexé

En février 2025, nous avons introduit la fonctionnalité d'indexation mise à jour (Catalogue indexé v2) que vous utilisez lors de la méthode de recherche et de restauration des données. La version précédente améliorait considérablement les performances d'indexation des données dans les environnements locaux. Avec cette version, le catalogue d'indexation est désormais disponible dans les environnements Amazon Web Services, Microsoft Azure et Google Cloud Platform (GCP).

Si vous êtes un nouveau client, le catalogue indexé v2 est activé par défaut pour tous les nouveaux environnements. Si vous êtes déjà client, vous pouvez réindexer votre environnement pour bénéficier du catalogue indexé v2.

.Comment activer l'indexation ?
Avant de pouvoir utiliser la méthode Search & Restore de restauration des données, vous devez activer l'« indexation » sur chaque environnement de travail source à partir duquel vous prévoyez de restaurer des volumes ou des fichiers. Sélectionnez l'option *Activer l'indexation* lorsque vous effectuez une recherche et une restauration.

Le catalogue indexé peut ensuite suivre chaque volume et fichier de sauvegarde, rendant vos recherches rapides et efficaces.

Pour plus d'informations, reportez-vous https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["Activer l'indexation pour la recherche et la restauration"]à .



==== Points de terminaison de liaison privée Azure et points de terminaison de service

En règle générale, la BlueXP backup and recovery établissent un point de terminaison privé avec le fournisseur de cloud pour gérer les tâches de protection. Cette version introduit un paramètre facultatif permettant d'activer ou de désactiver la création automatique d'un point de terminaison privé par la sauvegarde et la restauration BlueXP. Cela peut vous être utile si vous souhaitez davantage de contrôle sur le processus de création de points de terminaison privés.

Vous pouvez activer ou désactiver cette option lorsque vous activez la protection ou démarrez le processus de restauration.

Si vous désactivez ce paramètre, vous devrez créer manuellement le point de terminaison privé pour que la sauvegarde et la restauration BlueXP fonctionnent correctement. Sans une connectivité adéquate, vous risquez de ne pas pouvoir effectuer correctement les tâches de sauvegarde et de restauration.



==== Prise en charge de SnapMirror vers Cloud Resync sur ONTAP S3

La version précédente intégrait la prise en charge de SnapMirror to Cloud Resync (SM-C Resync). Cette fonctionnalité simplifie la protection des données lors de la migration de volumes dans les environnements NetApp. Cette version prend désormais en charge SM-C Resync sur ONTAP S3, ainsi que sur d'autres fournisseurs compatibles S3 tels que Wasabi et MinIO.



==== Apportez votre propre seau pour StorageGRID

Lorsque vous créez des fichiers de sauvegarde dans le stockage objet pour un environnement de travail, la sauvegarde et la restauration BlueXP créent par défaut le conteneur (bucket ou compte de stockage) pour les fichiers de sauvegarde dans le compte de stockage objet que vous avez configuré. Auparavant, vous pouviez remplacer cette configuration et spécifier votre propre conteneur pour Amazon S3, Azure Blob Storage et Google Cloud Storage. Avec cette version, vous pouvez désormais utiliser votre propre conteneur de stockage objet StorageGRID.

Voir https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["Créez votre propre conteneur de stockage d'objets"].



== Classement



=== 14 juillet 2025



==== Version 1.45

Cette version de BlueXP classification inclut des modifications de code qui optimisent l'utilisation des ressources et :

.Flux de travail amélioré pour ajouter des partages de fichiers pour la numérisation
Le flux de travail d'ajout de partages de fichiers à un groupe de partage de fichiers a été simplifié. Le processus différencie désormais la prise en charge du protocole CIFS selon le type d'authentification (Kerberos ou NTLM).

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["Analyser les partages de fichiers"].

.Informations améliorées sur le propriétaire du fichier
Vous pouvez désormais consulter plus d'informations sur les propriétaires des fichiers enregistrés dans l'onglet Investigation. Lorsque vous affichez les métadonnées d'un fichier dans l'onglet Enquête, recherchez le propriétaire du fichier, puis sélectionnez **Afficher les détails** pour voir le nom d'utilisateur, l'e-mail et le nom du compte SAM. Vous pouvez également consulter les autres éléments appartenant à cet utilisateur. Cette fonctionnalité est disponible uniquement pour les environnements de travail avec Active Directory.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Examinez les données stockées dans votre organisation"].



=== 10 juin 2025



==== Version 1.44

Cette version de classification BlueXP  inclut :

.Amélioration des temps de mise à jour du tableau de bord de gouvernance
Les délais de mise à jour des différents composants du tableau de bord de gouvernance ont été améliorés. Le tableau suivant présente la fréquence de mise à jour de chaque composant.

[cols="1,1"]
|===
| Composant | Heures de mise à jour 


| Âge des données | 24 heures 


| Catégories | 24 heures 


| Présentation des données | 5 minutes 


| Fichiers en double | 2 heures 


| Types de fichiers | 24 heures 


| Données non commerciales | 2 heures 


| Ouvrez autorisations | 24 heures 


| Recherches enregistrées | 2 heures 


| Données sensibles et autorisations étendues | 24 heures 


| Taille des données | 24 heures 


| Données obsolètes | 2 heures 


| Principaux référentiels de données par niveau de sensibilité | 2 heures 
|===
Vous pouvez consulter l'heure de la dernière mise à jour et mettre à jour manuellement les composants « Fichiers en double », « Données non commerciales », « Recherches enregistrées », « Données obsolètes » et « Principaux référentiels de données par niveau de sensibilité ». link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Afficher les détails de gouvernance sur les données stockées dans votre organisation"] .

.Améliorations des performances et de la sécurité
Des améliorations ont été apportées pour améliorer les performances, la consommation de mémoire et la sécurité de la classification BlueXP.

.Correctifs de bogues
Redis a été mis à niveau pour améliorer la fiabilité de la classification BlueXP. Cette dernière utilise désormais Elasticsearch pour améliorer la précision des rapports de nombre de fichiers lors des analyses.



=== 12 mai 2025



==== Version 1.43

Cette version de classification BlueXP  inclut :

.Hiérarchiser les analyses de classification
La classification BlueXP  permet de hiérarchiser les analyses cartographiques et de les classer en plus des acquisitions de mappage uniquement, ce qui vous permet de sélectionner les acquisitions qui sont effectuées en premier. La définition des priorités pour les acquisitions de carte et de classification est prise en charge pendant et avant le début des acquisitions. Si vous choisissez de hiérarchiser une acquisition pendant qu'elle est en cours, les acquisitions de mappage et de classification sont classées par ordre de priorité.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Hiérarchiser les acquisitions"].

.Prise en charge des catégories de données canadiennes d'information à caractère personnel (IIP)
Les analyses de classification BlueXP  identifient les catégories de données des RP au Canada. Ces catégories comprennent les renseignements bancaires, les numéros de passeport, les numéros d'assurance sociale, les numéros de permis de conduire et les numéros de carte santé pour toutes les provinces et tous les territoires du Canada.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Catégories de données personnelles"].

.Classification personnalisée (aperçu)
La classification BlueXP  prend en charge les classifications personnalisées pour les acquisitions Map & Classify. Grâce aux classifications personnalisées, vous pouvez personnaliser les analyses BlueXP  pour capturer des données spécifiques à votre entreprise à l'aide d'expressions régulières. Cette fonction est actuellement en aperçu.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["Ajouter des classifications personnalisées"].

.Onglet recherches enregistrées
L'onglet **politiques** a été renommé link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**Recherches enregistrées**"]. La fonctionnalité reste inchangée.

.Envoyer les événements d'analyse à la chronologie BlueXP 
La classification BlueXP  prend en charge l'envoi d'événements de classification (lorsqu'une analyse est lancée et qu'elle se termine) à link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Chronologie BlueXP"^].

.Mises à jour de sécurité
* Le paquet Keras a été mis à jour, atténuant les vulnérabilités (BDSA-2025-0107 et BDSA-2025-1984).
* La configuration des containers Docker a été mise à jour. Le conteneur n'a plus accès aux interfaces réseau de l'hôte pour l'élaboration de paquets réseau bruts. En réduisant les accès inutiles, la mise à jour limite les risques potentiels pour la sécurité.


.Amélioration des performances
Des améliorations de code ont été mises en œuvre pour réduire l'utilisation de la mémoire RAM et améliorer les performances globales de la classification BlueXP .

.Correctifs de bogues
Les bugs ayant provoqué l'échec des analyses StorageGRID, les options de filtre de la page d'enquête ne se chargent pas et l'évaluation de découverte de données ne pouvant pas être téléchargée pour les évaluations de volume élevé ont été corrigés.



=== 14 avril 2025



==== Version 1.42

Cette version de classification BlueXP  inclut :

.Balayage en vrac pour les environnements de travail
La classification BlueXP  prend en charge les opérations en bloc pour les environnements de travail. Vous pouvez choisir d'activer les analyses de mappage, d'activer les analyses de mappage et de classification, de désactiver les analyses ou de créer une configuration personnalisée sur l'ensemble des volumes de l'environnement de travail. Si vous effectuez une sélection pour un volume individuel, elle remplace la sélection en bloc. Pour effectuer une opération en bloc, accédez à la page **Configuration** et faites votre sélection.

.Télécharger le rapport d'enquête localement
La classification BlueXP  permet de télécharger des rapports d'enquête de données localement à afficher dans le navigateur. Si vous choisissez l'option locale, l'investigation de données est uniquement disponible au format CSV et n'affiche que les 10,000 premières lignes de données.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["Analysez les données stockées dans votre entreprise avec la classification BlueXP"].



=== 10 mars 2025



==== Version 1.41

Cette version de classification BlueXP  inclut des améliorations générales et des correctifs. Elle comprend également :

.État de l'acquisition
La classification BlueXP  suit la progression en temps réel des acquisitions de cartographie et de classification _initial_ sur un volume. Des barres progressives séparées suivent les analyses de cartographie et de classification, présentant un pourcentage du total des fichiers analysés. Vous pouvez également passer le curseur de la souris sur une barre de progression pour afficher le nombre de fichiers analysés et le nombre total de fichiers. Le suivi de l'état de vos analyses permet d'obtenir des informations plus détaillées sur la progression de l'analyse, ce qui vous permet de mieux planifier vos analyses et de comprendre l'allocation des ressources.

Pour afficher l'état de vos acquisitions, accédez à **Configuration** dans la classification BlueXP , puis sélectionnez la **Configuration de l'environnement de travail**. La progression est affichée en ligne pour chaque volume.



=== 19 février 2025



==== Version 1.40

Cette version de classification BlueXP  inclut les mises à jour suivantes.

.Prise en charge de RHEL 9.5
Cette version prend en charge Red Hat Enterprise Linux v9.5 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 et 9.5.

.Prioriser les acquisitions de mappage uniquement
Lorsque vous effectuez des acquisitions de mappage uniquement, vous pouvez hiérarchiser les acquisitions les plus importantes. Cette fonction vous aide lorsque vous disposez de nombreux environnements de travail et que vous souhaitez vous assurer que les numérisations à haute priorité sont effectuées en premier.

Par défaut, les analyses sont mises en file d'attente en fonction de l'ordre dans lequel elles sont initiées. Avec la possibilité de hiérarchiser les numérisations, vous pouvez déplacer les numérisations vers l'avant de la file d'attente. Plusieurs acquisitions peuvent être classées par ordre de priorité. La priorité est désignée dans un ordre de premier entrée et de premier sortie, ce qui signifie que la première analyse prioritaire se déplace vers l'avant de la file d'attente ; la deuxième analyse prioritaire devient la deuxième dans la file d'attente, etc.

La priorité est accordée une fois. Les nouvelles analyses automatiques des données de mappage sont effectuées dans l'ordre par défaut.

La priorisation est limitée à link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["analyses de mappage uniquement"^]; elle n'est pas disponible pour les acquisitions de cartes et de classification.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Hiérarchiser les acquisitions"^].

.Réessayez toutes les acquisitions
La classification BlueXP  prend en charge la possibilité de répéter par lots toutes les acquisitions ayant échoué.

Vous pouvez relancer des acquisitions en mode batch avec la fonction **Réessayer tout**. Si les analyses de classification échouent en raison d'un problème temporaire, tel qu'une panne réseau, vous pouvez réessayer toutes les analyses en même temps à l'aide d'un seul bouton au lieu de les essayer à nouveau individuellement. Les acquisitions peuvent être relancées autant de fois que nécessaire.

Pour réessayer toutes les acquisitions :

. Dans le menu BlueXP  Classification, sélectionnez *Configuration*.
. Pour réessayer toutes les acquisitions ayant échoué, sélectionnez *Réessayer toutes les acquisitions*.


.Amélioration de la précision du modèle de catégorisation
La précision du modèle de machine learning du link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["catégories prédéfinies"] a augmenté de 11 %.



=== 22 janvier 2025



==== Version 1.39

Cette version de classification BlueXP  met à jour le processus d'exportation du rapport d'investigation de données. Cette mise à jour d'exportation est utile pour effectuer des analyses supplémentaires sur vos données, créer des visualisations supplémentaires sur les données ou partager les résultats de votre enquête de données avec d'autres personnes.

Auparavant, l'exportation du rapport d'investigation de données était limitée à 10,000 lignes. Avec cette version, la limite a été supprimée afin que vous puissiez exporter toutes vos données. Cette modification vous permet d'exporter davantage de données à partir de vos rapports d'investigation de données, vous offrant ainsi une plus grande flexibilité dans votre analyse de données.

Vous pouvez choisir l'environnement de travail, les volumes, le dossier de destination et le format JSON ou CSV. Le nom de fichier exporté inclut un horodatage qui vous aide à identifier le moment où les données ont été exportées.

Les environnements de travail pris en charge sont les suivants :

* Cloud Volumes ONTAP
* FSX pour ONTAP
* ONTAP
* Partager le groupe


L'exportation de données à partir du rapport d'investigation de données comporte les limites suivantes :

* Le nombre maximum d'enregistrements à télécharger est de 500 millions. Par type (fichiers, répertoires et tables)
* L'exportation d'un million de documents devrait prendre environ 35 minutes.


Pour plus de détails sur l'investigation des données et le rapport, voir https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Analysez les données stockées dans votre entreprise"].



=== 16 décembre 2024



==== Version 1.38

Cette version de classification BlueXP  inclut des améliorations générales et des correctifs.



== Cloud Volumes ONTAP



=== 14 juillet 2025



==== Prise en charge du proxy transparent

BlueXP prend désormais en charge les serveurs proxy transparents en plus des connexions proxy explicites existantes. Lors de la création ou de la modification du connecteur BlueXP , vous pouvez configurer un serveur proxy transparent pour gérer en toute sécurité le trafic réseau vers et depuis Cloud Volumes ONTAP.

Pour plus d'informations sur l'utilisation des serveurs proxy dans Cloud Volumes ONTAP, reportez-vous à :

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-aws.html#network-configurations-to-support-connector-proxy-servers["Configurations réseau pour prendre en charge le proxy Connector dans AWS"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/azure/reference-networking-azure.html#network-configurations-to-support-connector["Configurations réseau pour prendre en charge le proxy Connector dans Azure"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#network-configurations-to-support-connector-proxy["Configurations réseau pour prendre en charge le proxy Connector dans Google Cloud"^]




==== Nouveau type de machine virtuelle pris en charge pour Cloud Volumes ONTAP dans Azure

À partir de Cloud Volumes ONTAP 9.13.1, L8s_v3 est pris en charge en tant que type de machine virtuelle dans les zones de disponibilité uniques et multiples Azure, pour les déploiements de paires haute disponibilité (HA) nouveaux et existants.

Pour plus d'informations, reportez-vous https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurations prises en charge dans Azure"^]à .



=== 25 juin 2025



==== Disponibilité restreinte des licences BYOL pour Cloud Volumes ONTAP

À compter du 25 juin 2025, NetApp a restreint le modèle de licence BYOL (Bring Your Own License) pour Cloud Volumes ONTAP. Cette restriction s'applique à tous les clients et déploiements Cloud Volumes ONTAP sur AWS, Azure et Google Cloud. Les seules exceptions concernent les clients du secteur public américain et les déploiements en Chine.

Le support et les services NetApp seront maintenus jusqu'à l'expiration de votre contrat BYOL, mais vos licences expirées ne seront ni renouvelées ni prolongées. À l'expiration de vos licences BYOL, vous devrez les remplacer par des licences basées sur la capacité, achetées via vos abonnements à la place de marché cloud. Un modèle de licence basé sur la capacité, via les places de marché hyperscale, simplifie l'expérience de licence et offre de meilleurs avantages commerciaux. Contactez votre équipe de comptes NetApp ou vos représentants du service client pour discuter des options de conversion.

Pour plus d'informations, reportez-vous à ce communiqué client :  https://mysupport.netapp.com/info/communications/CPC-00661.html["CPC-00661 : Modifications de la politique BYOL de Cloud Volumes ONTAP"^] .



=== 29 mai 2025



==== Déploiements en mode privé activés pour Cloud Volumes ONTAP 9.15.1

Vous pouvez désormais déployer Cloud Volumes ONTAP 9.15.1 en mode privé sur AWS, Azure et Google Cloud. Ce mode est activé pour les déploiements à nœud unique et haute disponibilité (HA) de Cloud Volumes ONTAP 9.15.1.

Pour plus d'informations sur les déploiements en mode privé, reportez-vous https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["Découvrez les modes de déploiement BlueXP"^]à la section .



== Copie et synchronisation



=== 2 février 2025



==== Nouvelle prise en charge du système d'exploitation pour le courtier de données

Le courtier de données est désormais pris en charge sur les hôtes exécutant Red Hat Enterprise 9.4, Ubuntu 23.04 et Ubuntu 24.04.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Afficher la configuration requise pour l'hôte Linux"].



=== 27 octobre 2024



==== Correctifs de bogues

Nous avons mis à jour le service de copie et de synchronisation BlueXP ainsi que le courtier en données pour corriger quelques bugs. La nouvelle version du courtier de données est 1.0.56.



=== 16 septembre 2024



==== Correctifs de bogues

Nous avons mis à jour le service de copie et de synchronisation BlueXP ainsi que le courtier en données pour corriger quelques bugs. La nouvelle version du courtier de données est 1.0.55.



== Conseiller digital



=== 06 août 2025



==== Prise en charge des commutateurs autorisés

Vous pouvez désormais afficher des informations sur les commutateurs SAN Brocade Fibre Channel éligibles au support. Cela inclut des détails sur le modèle de commutateur, le numéro de série et l'état de l'assistance. link:https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html["Apprenez à afficher les commutateurs autorisés du support"] .



==== Seuil pour les données RSS AutoSupport

La limite d'envoi récemment arrêté (RSS), dans le widget AutoSupport , a été étendue de 48 heures (2 jours) à 216 heures (9 jours) avant qu'un système ne soit signalé comme RSS. Ceci est fait pour s'adapter aux plateformes comme StorageGRID qui n'envoient que des données AutoSupport hebdomadaires.



==== Section API obsolète dans le catalogue API de Digital Advisor

Une nouvelle section API obsolète est disponible dans le catalogue API de Digital Advisor . Il répertorie les API dont l'obsolescence est prévue, ainsi que les calendriers d'obsolescence et les API alternatives.



==== Obsolescence des modules API de prévision de capacité V2 et de fin de support

Les modules API de prévision de capacité V2 et de fin de support sont prévus pour être obsolètes. Pour accéder aux API obsolètes ou pour connaître les délais d'obsolescence et les API alternatives, accédez à *Services API -> Parcourir -> API obsolètes*.



=== 09 juillet 2025



==== Upgrade Advisor

* Une option de téléchargement multiformat a été ajoutée pour les plans Upgrade Advisor afin de simplifier la planification des mises à niveau ONTAP et de résoudre les problèmes potentiels de blocage ou d'avertissement. Vous pouvez désormais télécharger les plans Upgrade Advisor aux formats Excel, PDF et JSON.
* Dans le format Excel du plan Upgrade Advisor, les améliorations suivantes ont été apportées :
+
** Vous pouvez consulter les pré-vérifications effectuées sur le cluster et signaler les résultats avec des indicateurs tels que « Réussi », « Échec » ou « Ignoré ». Cela garantit que le cluster est dans des conditions optimales pour terminer la mise à niveau ONTAP .
** Vous pouvez afficher les dernières mises à jour du micrologiciel recommandées applicables au cluster, ainsi que la version fournie avec la version cible ONTAP .
** Un nouvel onglet a été ajouté pour vérifier l'interopérabilité des clusters SAN. Il affiche les versions du système d'exploitation hôte prises en charge pour la version ONTAP cible sélectionnée.






=== 08 mai 2025



==== Widget AutoSupport

Le widget AutoSupport a été amélioré pour inclure une fenêtre contextuelle qui fournit des détails sur les systèmes qui ont cessé d'envoyer des données AutoSupport. L'activation de AutoSupport réduit les risques de temps d'indisponibilité et favorise la gestion proactive de l'état du système.



==== Rapport sur les contrats de support

Le rapport sur les contrats de support a été amélioré pour inclure le nouveau champ d'indicateur ASP/LSG. Ce champ vous permet de filtrer et d'identifier les systèmes couverts par un partenaire de support agréé, également appelé Lifecycle Services Certified.



==== Tableau de bord durabilité

Vous pouvez maintenant lancer le tableau de bord Sustainability à l'aide du lien inclus dans la présentation Sustainability.



== Portefeuille digital



=== 10 mars 2025



==== Possibilité de supprimer des abonnements

Vous pouvez désormais supprimer les abonnements du portefeuille numérique si vous ne vous y êtes plus abonné.



==== Afficher la capacité consommée pour les abonnements Marketplace

Lorsque vous consultez les abonnements PAYGO, vous pouvez maintenant afficher la capacité consommée de l'abonnement.



=== 10 février 2025

Le portefeuille digital BlueXP  a été repensé pour être facile à utiliser. Il offre désormais une gestion supplémentaire des abonnements et des licences.



==== Nouveau tableau de bord vue d'ensemble

La page d'accueil du portefeuille digital comprend un tableau de bord mis à jour de vos licences NetApp et de vos abonnements Marketplace. Vous pouvez ainsi zoomer sur les services, les types de licences et les actions requises.



==== Configuration des abonnements aux informations d'identification

Le portefeuille numérique BlueXP  vous permet désormais de configurer vos abonnements aux informations d'identification du fournisseur. En général, vous le faites lors de votre premier abonnement à un abonnement Marketplace ou à un contrat annuel. Auparavant, la modification des informations d'identification de l'abonnement ne pouvait être effectuée que sur la page informations d'identification.



==== Association d'abonnements à des organisations

Vous pouvez maintenant mettre à jour l'organisation à laquelle un abonnement est associé directement depuis le portefeuille digital.



==== Gestion des licences Cloud volumes ONTAP

Vous gérez maintenant les licences Cloud Volumes ONTAP via la page d'accueil ou l'onglet *licences directes*. Utilisez l'onglet *abonnements Marketplace* pour afficher les informations relatives à votre abonnement.



=== 5 mars 2024



==== Reprise d'activité BlueXP

Le portefeuille digital BlueXP vous permet désormais de gérer les licences pour la reprise d'activité BlueXP. Vous pouvez ajouter des licences, mettre à jour des licences et afficher des détails sur la capacité sous licence.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Découvrez comment gérer les licences des services de données BlueXP"]



=== 30 juillet 2023



==== Améliorations apportées aux rapports d'utilisation

Plusieurs améliorations apportées aux rapports d'utilisation de Cloud Volumes ONTAP sont désormais disponibles :

* L'unité TIB est désormais incluse dans le nom des colonnes.
* Un nouveau champ _node(s)_ pour les numéros de série est maintenant inclus.
* Une nouvelle colonne _Workload Type_ est désormais incluse dans le rapport d'utilisation des machines virtuelles de stockage.
* Les noms des environnements de travail sont désormais inclus dans les rapports Storage VM et Volume usage.
* Le type de volume _file_ est maintenant nommé _Primary (Read/Write)_.
* Le type de volume _secondary_ est maintenant appelé _Secondary (DP)_.


Pour plus d'informations sur les rapports d'utilisation, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Télécharger les rapports d'utilisation"].



== Reprise après incident



=== 14 juillet 2025

Version 4.2.5



==== Rôles des utilisateurs dans la BlueXP disaster recovery

La BlueXP disaster recovery utilise désormais des rôles pour gérer l’accès de chaque utilisateur à des fonctionnalités et actions spécifiques.

Le service utilise les rôles suivants qui sont spécifiques à la BlueXP disaster recovery.

* *Administrateur de récupération après sinistre* : effectuez toutes les actions dans la BlueXP disaster recovery.
* *Administrateur de basculement de reprise après sinistre* : effectuez des actions de basculement et de migration dans la BlueXP disaster recovery.
* *Administrateur d'application de récupération après sinistre* : Créez et modifiez des plans de réplication et démarrez des tests de basculement.
* *Visionneuse de récupération après sinistre* : affichez les informations dans la BlueXP disaster recovery, mais ne pouvez effectuer aucune action.


Si vous cliquez sur le service de BlueXP disaster recovery et le configurez pour la première fois, vous devez disposer de l'autorisation *SnapCenterAdmin* ou du rôle *Administrateur d'organisation*.

Pour plus de détails, voir  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Rôles et autorisations des utilisateurs dans la BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^].



==== Autres mises à jour de la BlueXP disaster recovery

* Découverte de réseau améliorée
* Améliorations de l'évolutivité :
+
** Filtrage des métadonnées requises au lieu de tous les détails
** Améliorations de la découverte pour récupérer et mettre à jour les ressources des machines virtuelles plus rapidement
** Optimisation de la mémoire et des performances pour la récupération et la mise à jour des données
** Améliorations de la création de clients vCenter SDK et de la gestion des pools


* Gestion des données obsolètes lors de la prochaine découverte planifiée ou manuelle :
+
** Lorsqu'une machine virtuelle est supprimée dans vCenter, la BlueXP disaster recovery la supprime désormais automatiquement du plan de réplication.
** Lorsqu'une banque de données ou un réseau est supprimé dans vCenter, la BlueXP disaster recovery le supprime désormais du plan de réplication et du groupe de ressources.
** Lorsqu'un cluster, un hôte ou un centre de données est supprimé dans vCenter, la BlueXP disaster recovery le supprime désormais du plan de réplication et du groupe de ressources.


* Vous pouvez désormais accéder à la documentation Swagger en mode navigation privée. Vous pouvez y accéder depuis la BlueXP disaster recovery via Paramètres > Documentation API ou directement à l'URL suivante en mode navigation privée :  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentation Swagger"^] .
* Dans certains cas, après une restauration automatique, l'iGroup était conservé une fois l'opération terminée. Cette mise à jour supprime l'iGroup s'il est obsolète.
* Si le nom de domaine complet NFS était utilisé dans le plan de réplication, la BlueXP disaster recovery le résout désormais en adresse IP. Cette mise à jour est utile si le nom de domaine complet n'est pas résoluble sur le site de reprise après sinistre.
* Améliorations de l'alignement de l'interface utilisateur
* Améliorations du journal pour capturer les détails de dimensionnement de vCenter après la découverte réussie




=== 30 juin 2025

Version 4.2.4P2



==== Améliorations de la découverte

Cette mise à jour améliore le processus de découverte, ce qui réduit le temps nécessaire à la découverte.



=== 23 juin 2025

Version 4.2.4P1



==== Améliorations du mappage des sous-réseaux

Cette mise à jour améliore la boîte de dialogue « Ajouter et modifier le mappage de sous-réseaux » avec une nouvelle fonctionnalité de recherche. Vous pouvez désormais trouver rapidement des sous-réseaux spécifiques en saisissant des termes de recherche, ce qui simplifie la gestion des mappages de sous-réseaux.



=== 9 juin 2025

Version 4.2.4



==== Prise en charge de la solution de mot de passe d'administrateur local Windows (LAPS)

Windows Local Administrator Password Solution (Windows LAPS) est une fonctionnalité Windows qui gère et sauvegarde automatiquement le mot de passe d'un compte administrateur local sur Active Directory.

Vous pouvez désormais sélectionner les options de mappage de sous-réseau et cocher l'option LAPS en fournissant les informations du contrôleur de domaine. Grâce à cette option, vous n'avez pas besoin de fournir de mot de passe pour chacune de vos machines virtuelles.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



== Systèmes E-Series



=== 12 mai 2025



==== Rôle d'accès BlueXP requis

Vous avez désormais besoin de l’un des rôles d’accès suivants pour afficher, découvrir ou gérer la série E dans BlueXP : administrateur d’organisation, administrateur de dossier ou de projet, administrateur de stockage ou spécialiste de l’intégrité du système.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]



=== 18 septembre 2022



==== Prise en charge des baies E-Series

Vous pouvez désormais découvrir vos systèmes E-Series directement à partir de BlueXP. La découverte des systèmes E-Series vous offre une vue complète des données dans l'ensemble de votre multicloud hybride.



== Efficacité économique



=== 15 mai 2024



==== Fonctionnalités désactivées

Certaines fonctionnalités d'efficacité économique de BlueXP  ont été temporairement désactivées :

* Mise à jour technologique
* Ajoutez de la capacité




=== 14 mars 2024



==== Options de mise à jour technologique

Si vous disposez de ressources existantes et souhaitez déterminer si une technologie doit être mise à jour, vous pouvez utiliser les options de mise à jour technologique d'efficacité économique BlueXP. Vous pouvez soit examiner une courte évaluation de vos workloads actuels et obtenir des recommandations, soit envoyer des journaux AutoSupport à NetApp au cours des 90 derniers jours, le service peut maintenant fournir une simulation des workloads pour voir les performances de vos workloads sur du nouveau matériel.

Vous pouvez également ajouter une charge de travail et exclure des charges de travail existantes de la simulation.

Auparavant, vous pouviez uniquement évaluer vos ressources et déterminer si une mise à jour technologique est recommandée ?

La fonction fait désormais partie de l'option Tech Refresh dans le menu de navigation de gauche.

En savoir plus sur https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Évaluer une mise à jour technologique"] le .



=== 08 novembre 2023



==== Mise à jour technologique

Cette version de BlueXP Economic Efficiency comprend une nouvelle option qui permet d'évaluer vos ressources et d'identifier si une mise à jour technologique est recommandée. Le service inclut une nouvelle option de mise à jour technologique dans le menu de navigation de gauche, de nouvelles pages sur lesquelles vous pouvez évaluer vos charges de travail et ressources actuelles, ainsi qu'un rapport qui vous fournit des recommandations.



== La mise en cache en périphérie

Le service de mise en cache BlueXP  Edge a été supprimé le 7 août 2024.



== Google Cloud NetApp volumes

Directive non résolue dans <stdin> - inclure : https://raw.githubusercontent.com/NetAppDocs/bluexp-google-cloud-netapp-volumes/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Google Cloud Storage



=== 10 juillet 2023



==== Possibilité d'ajouter de nouveaux compartiments et de gérer les compartiments existants à partir de BlueXP

Vous avez pu afficher les compartiments Google Cloud Storage sur le canevas BlueXP pendant un certain temps. Vous pouvez désormais ajouter de nouveaux compartiments et modifier les propriétés des compartiments existants directement à partir de BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["Découvrez comment ajouter de nouveaux compartiments de stockage Google Cloud"].



== Keystone



=== 05 août 2025



==== Afficher les données de consommation au niveau de l'instance

Vous pouvez afficher la consommation actuelle et les données historiques pour chaque instance de niveau de service de performance via le tableau de bord Keystone dans BlueXP. Cette fonctionnalité est disponible pour les niveaux de service de performances avec plusieurs instances, à condition que vous disposiez d'un abonnement Keystone version 3 (v3). Pour en savoir plus, consultezlink:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Consultez la consommation de vos abonnements Keystone"] .



== Kubernetes

La prise en charge de la détection et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.



== Rapports de migration

Le service de rapports de migration BlueXP  a été supprimé le 7 août 2024.



== Clusters ONTAP sur site



=== 12 mai 2025



==== Rôle d'accès BlueXP requis

Vous avez désormais besoin de l’un des rôles d’accès suivants pour afficher, découvrir ou gérer les clusters ONTAP sur site : administrateur d’organisation, administrateur de dossier ou de projet, administrateur de stockage ou spécialiste de l’intégrité du système. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]



=== 26 novembre 2024



==== Prise en charge des systèmes ASA r2 en mode privé

Vous pouvez désormais découvrir les systèmes NetApp ASA r2 lorsque vous utilisez BlueXP  en mode privé. Cette prise en charge est disponible à partir de la version 3.9.46 du mode privé de BlueXP .

* https://docs.netapp.com/us-en/asa-r2/index.html["En savoir plus sur les systèmes ASA r2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Découvrez les modes de déploiement BlueXP"^]




=== 7 octobre 2024



==== Prise en charge des systèmes ASA r2

Vous pouvez désormais découvrir les systèmes NetApp ASA r2 dans BlueXP  lorsque vous utilisez BlueXP  en mode standard ou en mode restreint. Une fois que vous avez découvert un système NetApp ASA r2 et ouvert votre environnement de travail, vous accédez directement à System Manager.

Aucune autre option de gestion n'est disponible avec les systèmes ASA r2. Vous ne pouvez pas utiliser la vue Standard et vous ne pouvez pas activer les services BlueXP.

La découverte des systèmes ASA r2 n'est pas prise en charge lorsque vous utilisez BlueXP  en mode privé.

* https://docs.netapp.com/us-en/asa-r2/index.html["En savoir plus sur les systèmes ASA r2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Découvrez les modes de déploiement BlueXP"^]




== Résilience opérationnelle



=== 02 avril 2023



==== Service de résilience opérationnelle BlueXP

Grâce au nouveau service de résilience opérationnelle BlueXP et à ses suggestions automatisées de résolution des problèmes opérationnels IT, vous pouvez implémenter des solutions suggérées avant une panne ou une défaillance.

La résilience opérationnelle est un service qui vous aide à analyser les alertes et les événements afin de préserver l'intégrité, la disponibilité et les performances des services et des solutions.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["En savoir plus sur la résilience opérationnelle de BlueXP"].



== Protection par ransomware



=== 15 juillet 2025



==== Prise en charge de la charge de travail SAN

Cette version inclut la prise en charge des charges de travail SAN dans la BlueXP ransomware protection. Vous pouvez désormais protéger les charges de travail SAN en plus des charges de travail NFS et CIFS.

Pour plus d'informations, reportez-vous link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Protection BlueXP contre les ransomware requise"]à .



==== Protection améliorée de la charge de travail

Cette version améliore le processus de configuration des charges de travail avec des stratégies de snapshots et de sauvegarde issues d'autres outils NetApp , tels que SnapCenter ou BlueXP backup and recovery. Dans les versions précédentes, la BlueXP ransomware protection détectait les stratégies d'autres outils, vous permettant uniquement de modifier la stratégie de détection. Avec cette version, vous pouvez désormais remplacer les stratégies de snapshots et de sauvegarde par des stratégies de BlueXP ransomware protection ou continuer à utiliser celles d'autres outils.

Pour plus de détails, reportez-vous à link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Protégez les workloads"].



==== Notifications par e-mail

Si la BlueXP ransomware protection détecte une attaque possible, une notification apparaît dans les notifications BlueXP et un e-mail est envoyé à l'adresse e-mail que vous avez configurée.

Cet e-mail contient des informations sur la gravité de l'attaque, la charge de travail impactée et un lien vers l'alerte dans l'onglet *Alertes* de la BlueXP ransomware protection .

Si vous avez configuré un système de gestion de la sécurité et des événements (SIEM) dans la BlueXP ransomware protection, le service envoie les détails de l'alerte à votre système SIEM.

Pour plus de détails, reportez-vous à link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gérer les alertes de ransomware détectées"].



=== 9 juin 2025



==== Mises à jour de la page de destination

Cette version inclut des mises à jour de la page de destination de la protection contre les ransomwares BlueXP qui facilitent le démarrage de l'essai gratuit et la découverte.



==== Mises à jour sur les exercices de préparation

Auparavant, vous pouviez exécuter un exercice de préparation aux ransomwares en simulant une attaque sur un nouvel échantillon de charge de travail. Grâce à cette fonctionnalité, vous pouvez analyser l'attaque simulée et récupérer la charge de travail. Utilisez cette fonctionnalité pour tester les notifications d'alerte, la réponse et la récupération. Exécutez et planifiez ces exercices aussi souvent que nécessaire.

Avec cette version, vous pouvez utiliser un nouveau bouton sur le tableau de bord de protection contre les ransomwares BlueXP pour exécuter un exercice de préparation aux ransomwares sur une charge de travail de test, ce qui vous permet de simuler plus facilement des attaques de ransomwares, d'étudier leur impact et de récupérer efficacement les charges de travail, le tout dans un environnement contrôlé.

Vous pouvez désormais exécuter des exercices de préparation sur les charges de travail CIFS (SMB) en plus des charges de travail NFS.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Évaluez le niveau de préparation à une attaque par ransomware"] .



==== Activer les mises à jour de classification BlueXP

Avant d'utiliser la classification BlueXP  dans le service de protection contre les ransomwares BlueXP , vous devez activer la classification BlueXP  pour analyser vos données. La classification des données vous aide à trouver des informations personnelles identifiables (PII), ce qui peut augmenter les risques de sécurité.

Vous pouvez déployer la classification BlueXP sur une charge de travail de partage de fichiers depuis la protection BlueXP contre les ransomwares. Dans la colonne *Exposition à la confidentialité*, sélectionnez l'option *Identifier l'exposition*. Si vous avez activé le service de classification, cette action identifie l'exposition. Sinon, avec cette version, une boîte de dialogue vous propose de déployer la classification BlueXP. Sélectionnez *Déployer* pour accéder à la page d'accueil du service de classification BlueXP, où vous pourrez déployer ce service. W

Pour plus de détails, reportez-vous à  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["Déployez la classification BlueXP dans le cloud"^] et pour utiliser le service dans le cadre de la protection contre les ransomwares BlueXP, reportez-vous à  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["Recherchez des informations à caractère personnel grâce à la classification BlueXP"] .



=== 13 mai 2025



==== Signalement d'environnements de travail non pris en charge dans la protection contre les ransomwares BlueXP

Au cours du workflow de découverte, la protection contre les ransomwares de BlueXP  fournit des informations supplémentaires lorsque vous survolez les workloads pris en charge ou non pris en charge. Ainsi, vous comprendrez pourquoi certains de vos workloads ne sont pas découverts par le service de protection BlueXP  contre les ransomware.

Il existe de nombreuses raisons pour lesquelles le service ne prend pas en charge un environnement de travail. Par exemple, la version ONTAP de votre environnement de travail peut être inférieure à la version requise. Lorsque vous placez le pointeur de la souris sur un environnement de travail non pris en charge, une info-bulle affiche la raison.

Vous pouvez afficher les environnements de travail non pris en charge lors de la découverte initiale, où vous pouvez également télécharger les résultats. Vous pouvez également afficher les résultats de la découverte à partir de l'option *Workload Discovery* de la page Paramètres.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Découvrez les workloads dans la solution de protection BlueXP contre les ransomwares"] .



=== 29 avril 2025



==== Prise en charge d'Amazon FSX pour NetApp ONTAP

Cette version prend en charge Amazon FSX pour NetApp ONTAP. Cette fonctionnalité vous aide à protéger vos workloads FSX pour ONTAP avec la protection contre les ransomware BlueXP .

FSX pour ONTAP est un service entièrement géré qui offre la puissance du stockage NetApp ONTAP dans le cloud. Il fournit les mêmes fonctionnalités, performances et fonctionnalités d'administration que sur site, avec l'agilité et l'évolutivité d'un service AWS natif.

Les modifications suivantes ont été apportées au workflow de protection contre les ransomwares de BlueXP  :

* La découverte inclut les workloads dans FSX pour les environnements de travail ONTAP 9.15.
* L'onglet protection affiche les workloads dans les environnements FSX pour ONTAP. Dans cet environnement, vous devez effectuer des opérations de sauvegarde à l'aide du service de sauvegarde FSX pour ONTAP. Vous pouvez restaurer ces workloads à l'aide des snapshots de protection contre les ransomwares de BlueXP .
+

TIP: Les stratégies de sauvegarde d'un workload s'exécutant sur FSX pour ONTAP ne peuvent pas être définies dans BlueXP . Toutes les stratégies de sauvegarde existantes définies dans Amazon FSX pour NetApp ONTAP restent inchangées.

* Les incidents d'alerte affichent le nouvel environnement de travail FSX pour ONTAP.


Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Découvrez la protection contre les ransomwares de BlueXP  et les environnements de travail"] .

Pour plus d'informations sur les options prises en charge, reportez-vous au https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Limites de la protection contre les ransomware de BlueXP"].



==== Rôle d'accès BlueXP requis

Vous avez désormais besoin de l’un des rôles d’accès suivants pour afficher, découvrir ou gérer la protection contre les ransomwares BlueXP : administrateur de l’organisation, administrateur de dossier ou de projet, administrateur de la protection contre les ransomwares ou visualiseur de protection contre les ransomwares.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès BlueXP pour tous les services"^].



=== 14 avril 2025



==== Rapports d'exercice de préparation

Avec cette version, vous pouvez consulter des rapports d'exploration de la préparation aux attaques par ransomware. Une exploration de la préparation vous permet de simuler une attaque par ransomware sur un workload échantillon nouvellement créé. Ensuite, étudiez l'attaque simulée et restaurez la charge de travail de l'échantillon. Cette fonctionnalité vous aide à être sûr d'être préparé en cas d'attaque par ransomware réelle en testant les processus de notification d'alerte, de réponse et de restauration.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Évaluez le niveau de préparation à une attaque par ransomware"] .



==== Nouveaux rôles et autorisations de contrôle d'accès basés sur des rôles

Vous pouviez auparavant attribuer des rôles et des autorisations à des utilisateurs en fonction de leurs responsabilités, ce qui vous aidera à gérer l'accès des utilisateurs à la protection contre les ransomwares de BlueXP . Avec cette version, il existe deux nouveaux rôles spécifiques à la protection contre les ransomwares BlueXP  avec des autorisations mises à jour. Les nouveaux rôles sont :

* Administrateur de la protection contre les ransomwares
* Visualiseur de protection contre les ransomware


Pour plus d'informations sur les autorisations, reportez-vous https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["La protection BlueXP  contre les ransomwares permet un accès basé sur des rôles aux fonctionnalités"] à la section .



==== Améliorations de paiement

Cette version comprend plusieurs améliorations du processus de paiement.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Configurez les options de licence et de paiement"] .



== Résolution

Le service de correction BlueXP a été supprimé le 22 avril 2024.



== La réplication



=== 18 septembre 2022



==== FSX pour ONTAP vers Cloud Volumes ONTAP

Vous pouvez désormais répliquer des données d'un système de fichiers Amazon FSX pour ONTAP vers Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Découvrez comment configurer la réplication des données"].



=== 31 juillet 2022



==== FSX pour ONTAP en tant que source de données

Vous pouvez désormais répliquer des données d'un système de fichiers Amazon FSX pour ONTAP vers les destinations suivantes :

* Amazon FSX pour ONTAP
* Cluster ONTAP sur site


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Découvrez comment configurer la réplication des données"].



=== 2 septembre 2021



==== Prise en charge d'Amazon FSX pour ONTAP

Vous pouvez désormais répliquer des données à partir d'un système Cloud Volumes ONTAP ou d'un cluster ONTAP sur site vers un système de fichiers Amazon FSX pour ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Découvrez comment configurer la réplication des données"].



== Mises à jour de logiciels



=== 12 mai 2025



==== Rôle d'accès BlueXP requis

Vous devez désormais disposer de l'un des rôles d'accès suivants pour installer les mises à jour logicielles : *Administrateur de l'organisation*, *Administrateur de dossier ou de projet*, *Administrateur du stockage*, *Observateur du stockage* ou *Spécialiste de l'intégrité du stockage*. Les utilisateurs disposant du rôle d'observateur du stockage disposent de diverses autorisations liées aux mises à jour logicielles, mais ne peuvent pas les installer. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]



=== 02 avril 2025



==== Risques atténués

Dans la section récapitulative des mises à jour logicielles BlueXP , vous pouvez maintenant afficher le nombre total de risques pouvant être atténués par la mise à jour du système d'exploitation. Cela permet aux utilisateurs d'évaluer les améliorations de sécurité et de stabilité de leur base d'installation.



=== 07 août 2024



==== Mise à jour ONTAP

Le service de mises à jour logicielles BlueXP  offre aux utilisateurs une expérience de mise à jour fluide en limitant les risques et en leur permettant d'exploiter pleinement les fonctionnalités ONTAP.

En savoir plus sur link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Mises à jour du logiciel BlueXP"].



== StorageGRID



=== 12 mai 2025



==== Rôles d'accès BlueXP nécessaires

Vous avez désormais besoin de l'un des rôles d'accès suivants pour afficher, découvrir ou gérer StorageGRID dans BlueXP: *Administrateur d'organisation*, *Administrateur de dossier ou de projet*, *Administrateur de stockage* ou *Spécialiste de l'état du stockage*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]



=== 7 août 2024



==== Nouvelle vue avancée

À partir de StorageGRID 11.8, vous pouvez utiliser l'interface familière du Gestionnaire de grille pour gérer votre système StorageGRID à partir de BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Découvrez comment gérer StorageGRID à l'aide de la vue avancée"].



==== Possibilité d'examiner et d'approuver le certificat d'interface de gestion StorageGRID

Vous avez désormais la possibilité d'examiner et d'approuver un certificat d'interface de gestion StorageGRID lors de la découverte du système StorageGRID à partir de BlueXP . Vous pouvez également vérifier et approuver le dernier certificat d'interface de gestion StorageGRID sur une grille découverte.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Découvrez comment vérifier et approuver le certificat du serveur lors de la découverte du système."]



=== 18 septembre 2022



==== Prise en charge de StorageGRID

Vous pouvez désormais découvrir vos systèmes StorageGRID directement depuis BlueXP. La découverte de StorageGRID vous offre une vue complète sur les données dans l'ensemble de votre environnement multicloud hybride.



== Tiering



=== 9 août 2023



==== Utilisez un préfixe personnalisé pour le nom du compartiment

Auparavant, vous aviez besoin d'utiliser le préfixe par défaut « fabric-pool » lors de la définition du nom du compartiment, par exemple, _fabric-pool-bucket1_. Vous pouvez désormais utiliser un préfixe personnalisé pour nommer votre compartiment. Cette fonctionnalité n'est disponible que lors du Tiering des données vers Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["En savoir plus >>"].



==== Recherchez un cluster sur tous les connecteurs BlueXP

Si vous utilisez plusieurs connecteurs pour gérer tous les systèmes de stockage de votre environnement, certains clusters sur lesquels vous souhaitez implémenter la hiérarchisation peuvent se trouver dans différents connecteurs. Si vous n'êtes pas sûr de quel connecteur gère un certain cluster, vous pouvez rechercher sur tous les connecteurs à l'aide du Tiering BlueXP. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["En savoir plus >>"].



=== 4 juillet 2023



==== Réglez la bande passante pour transférer les données inactives

Lorsque vous activez le Tiering BlueXP, ONTAP peut utiliser une quantité illimitée de bande passante réseau pour transférer les données inactives des volumes du cluster vers le stockage objet. Si vous remarquez que le trafic de hiérarchisation affecte les charges de travail normales des utilisateurs, vous pouvez limiter la quantité de bande passante qui peut être utilisée pendant le transfert. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["En savoir plus >>"].



==== Événement de hiérarchisation affiché dans le Centre de notification

La fonctionnalité de Tiering « transférer des données supplémentaires d'une <name> de cluster vers un stockage objet pour améliorer votre efficacité du stockage » s'affiche désormais sous forme de notification lorsqu'un cluster effectue le Tiering de moins de 20 % de ses données inactives, y compris les clusters qui ne hiérarchise aucune donnée.

Cette notification est une « recommandation » pour vous aider à rendre vos systèmes plus efficaces et à réduire vos coûts de stockage. Il fournit un lien vers le https://bluexp.netapp.com/cloud-tiering-service-tco["Calculateur de coût total de possession et d'économies du Tiering BlueXP"^] pour vous aider à calculer vos économies.



=== 3 avril 2023



==== L'onglet licences a été supprimé

L'onglet Licensing a été supprimé de l'interface de Tiering BlueXP. Toutes les licences pour les abonnements PAYGO sont maintenant accessibles depuis le tableau de bord du Tiering BlueXP sur site. Il existe également un lien vers le portefeuille digital BlueXP depuis cette page pour afficher et gérer n'importe quel modèle de Tiering BlueXP BYOL (Bring Your Own License).



==== Les onglets de hiérarchisation ont été renommés et mis à jour

L'onglet « clusters » a été renommé « clusters » et l'onglet « Présentation sur site » a été renommé « Tableau de bord sur site ». Ces pages ont ajouté des informations qui vous aideront à déterminer si vous pouvez optimiser votre espace de stockage avec une configuration de hiérarchisation supplémentaire.



== Mise en cache du volume



=== 04 juin 2023



==== Mise en cache du volume

La mise en cache des volumes, fonctionnalité du logiciel ONTAP 9, est une fonctionnalité de mise en cache à distance qui simplifie la distribution des fichiers et réduit la latence des réseaux WAN en rapprochant vos utilisateurs et vos ressources de calcul, tout en réduisant les coûts de la bande passante WAN. La mise en cache du volume fournit un volume inscriptible persistant à un emplacement distant. Vous pouvez utiliser la mise en cache du volume BlueXP pour accélérer l'accès aux données ou pour décharger le trafic des volumes fortement sollicités. Les volumes de cache sont parfaitement adaptés aux charges de travail exigeant une capacité de lecture maximale, en particulier lorsque les clients doivent accéder aux mêmes données de manière répétée.

La mise en cache des volumes BlueXP vous offre des fonctionnalités de mise en cache pour le cloud, en particulier pour Amazon FSX pour NetApp ONTAP, Cloud Volumes ONTAP et pour vos environnements de travail sur site.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["En savoir plus sur la mise en cache de volumes BlueXP"].



== Usine de charge de travail



=== 29 juin 2025



==== Mise à jour des autorisations pour les bases de données

L'autorisation suivante est désormais disponible en mode _lecture seule_ pour les bases de données :  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



==== Prise en charge du service de notification de l'usine de charge de travail BlueXP

Le service de notification de l'usine de charge de travail BlueXP permet à l'usine de charge de travail d'envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications de l'usine de charge de travail BlueXP"]



=== 04 mai 2025



==== Prise en charge de CloudShell avec remplissage automatique

Lorsque vous utilisez BlueXP  Workload Factory CloudShell, vous pouvez commencer à taper une commande et appuyer sur la touche Tab pour afficher les options disponibles. S'il existe plusieurs possibilités, l'interface de ligne de commande affiche une liste de suggestions. Cette fonction améliore la productivité en réduisant au minimum les erreurs et en accélérant l'exécution des commandes.



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== 30 mars 2025



==== CloudShell signale les réponses d'erreur générées par l'IA pour les commandes de l'interface de ligne de commande ONTAP

Lorsque vous utilisez CloudShell, chaque fois que vous exécutez une commande de l'interface de ligne de commande ONTAP et qu'une erreur se produit, vous pouvez obtenir des réponses d'erreur générées par l'IA incluant une description de l'échec, la cause de l'échec et une résolution détaillée.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== iam:mise à jour des autorisations SimulatePermissionPolicy

Vous pouvez désormais gérer les `iam:SimulatePrincipalPolicy` autorisations à partir de la console d'usine des charges de travail lorsque vous ajoutez des informations d'identification de compte AWS supplémentaires ou que vous ajoutez une nouvelle fonctionnalité de charge de travail telle que la charge de travail GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



=== 02 février 2025



==== CloudShell est disponible dans la console d'usine des charges de travail BlueXP

CloudShell est disponible à partir de n'importe quel emplacement de la console d'usine de la charge de travail BlueXP . CloudShell vous permet d'utiliser les informations d'identification AWS et ONTAP que vous avez fournies dans votre compte BlueXP  et d'exécuter les commandes de la CLI AWS ou les commandes de la CLI ONTAP dans un environnement de type shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== Mise à jour des autorisations pour les bases de données

L'autorisation suivante est maintenant disponible en _read_ mode pour les bases de données : `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]
