---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam' 
summary: Découvrez les derniers changements apportés aux services Cloud intégrés à la plateforme BlueXP. 
---
= Changements récents dans BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les derniers changements apportés aux services Cloud intégrés à la plateforme BlueXP. Pour consulter l'historique complet des versions, accédez au link:release-notes-index.html["ensemble complet de notes de version"] pour chaque service.



== Fonctionnalités administratives

Cette section décrit les nouvelles fonctionnalités liées aux fonctions d'administration de BlueXP : comptes, connecteurs, informations d'identification du fournisseur cloud, etc.



=== 14 avril 2025



==== Connecteur 3.9.51

Cette version de BlueXP Connector inclut des améliorations mineures de la sécurité et des correctifs.

À ce stade, la version 3.9.51 est disponible pour le mode standard et le mode restreint.



==== Gestion des identités et des accès BlueXP

* Pour accéder à la protection contre les ransomware, les utilisateurs ne disposant pas d'un rôle d'administrateur d'organisation ou de dossier ou de projet doivent se voir attribuer un rôle de protection contre les ransomwares. Vous pouvez attribuer un utilisateur à l'un des deux rôles suivants : administrateur de la protection contre les ransomware ou visualiseur de la protection contre les ransomware.
* Les utilisateurs ne disposant pas d'un administrateur Org, d'un dossier ou d'un administrateur de projet doivent se voir attribuer un rôle Keystone pour avoir accès à Keystone. Vous pouvez attribuer un utilisateur à l'un des deux rôles suivants : admin Keystone ou visionneur Keystone.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès."^]

* Si vous disposez du rôle d'administrateur Org, dossier ou projet, vous pouvez désormais associer un abonnement Keystone à un projet IAM. L'association d'un abonnement Keystone à un projet IAM vous permet de contrôler l'accès à Keystone dans BlueXP .




=== 28 mars 2025



==== Version en mode privé (3.9.50)

Une nouvelle version en mode privé est désormais disponible au téléchargement sur le https://mysupport.netapp.com/site/downloads["Site de support NetApp"^]

La version 3.9.50 comprend des mises à jour des composants et services BlueXP  suivants.

[cols="3*"]
|===
| Composant ou service | Version incluse dans cette version | Modifications depuis la version précédente du mode privé 


| Connecteur | 3.9.50, 3.9.49 | Accédez au https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Nouveautés de la page BlueXP  Connector"] et reportez-vous aux modifications incluses pour les versions 3.9.50 et 3.9.49. 


| Sauvegarde et restauration | 17 mars 2025 | Accédez au et consultez les modifications incluses dans la https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Nouveautés de la page sauvegarde et restauration BlueXP"^] version de mars 2024. 


| Classement | 10 mars 2025 (version 1.41) | Accédez au et consultez les changements inclus dans les https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Nouveautés de la page de classification BlueXP"^] versions 1.38 à 1.371.41. 
|===
Pour plus d'informations sur le mode privé, notamment sur la mise à niveau, reportez-vous aux sections suivantes :

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["En savoir plus sur le mode privé"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Découvrez comment démarrer avec BlueXP en mode privé"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Apprenez à mettre à niveau le connecteur lorsque vous utilisez le mode privé"]




=== 10 mars 2025



==== Connecteur 3.9.50

Cette version de BlueXP Connector inclut des améliorations mineures de la sécurité et des correctifs.

À ce stade, la version 3.9.50 est disponible pour le mode standard et le mode restreint.



==== Version bêta de NetApp Keystone disponible dans BlueXP

NetApp Keystone sera bientôt disponible sur BlueXP  et est maintenant en version bêta. Vous pouvez accéder à la page d'inscription de la version bêta de NetApp Keystone à partir de la barre de navigation de gauche de BlueXP .



== Alertes



=== 7 octobre 2024



==== Page de liste des alertes BlueXP

Vous pouvez rapidement identifier les clusters ONTAP dont la capacité est faible ou les performances sont faibles, évaluer l'étendue de la disponibilité et identifier les risques de sécurité. Vous pouvez afficher les alertes relatives à la capacité, aux performances, à la protection, à la disponibilité, à la sécurité et à la configuration.



==== Détails des alertes

Vous pouvez explorer les détails des alertes et trouver des recommandations.



==== Afficher les détails du cluster liés à ONTAP System Manager

Avec les alertes BlueXP , vous pouvez consulter les alertes associées à votre environnement de stockage ONTAP et explorer les détails liés à ONTAP System Manager.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["En savoir plus sur les alertes BlueXP"].



== Amazon FSX pour ONTAP



=== 30 mars 2025



==== iam:mise à jour des autorisations SimulatePermissionPolicy

Vous pouvez désormais gérer l' `iam:SimulatePrincipalPolicy`autorisation depuis la console BlueXP  lorsque vous ajoutez des informations d'identification de compte AWS supplémentaires ou que vous ajoutez une nouvelle fonctionnalité de charge de travail telle que la charge de travail GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"^]



=== 02 mars 2025



==== Événements CloudShell dans Tracker

À chaque fois que vous utilisez CloudShell pour exécuter les opérations FSX for ONTAP à partir de workloads BlueXP , les événements apparaissent dans le module de suivi.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Découvrez comment surveiller et suivre les opérations FSX pour ONTAP dans BlueXP"^]



=== 02 février 2025



==== Associer le système de fichiers FSX pour ONTAP à un espace de travail dans BlueXP

Après l'intégration de BlueXP  en novembre 2024, les nouveaux systèmes de fichiers FSX pour ONTAP n'étaient associés à aucun espace de travail dans BlueXP . Désormais, lorsque vous créez ou découvrez des systèmes de fichiers FSX pour ONTAP, ils sont associés à un espace de travail au sein d'un compte BlueXP .

Si vous disposez déjà de systèmes de fichiers FSX pour ONTAP qui ne sont pas associés à un espace de travail, nous vous aiderons à les associer à un espace de travail dans BlueXP . Vous pouvez le link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["Créer un dossier de demande de support avec le support NetApp"^]faire à partir de la console BlueXP . Sélectionnez *Workload Factory* comme service.



==== Suppression du système de fichiers du canevas BlueXP

Vous pouvez maintenant supprimer un système de fichiers FSX pour ONTAP d'un espace de travail dans le canevas BlueXP . Cette opération dissocie le système de fichiers d'un espace de travail pour vous permettre de l'associer à un autre espace de travail dans le même compte BlueXP .

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["Découvrez comment supprimer un système de fichiers FSX pour ONTAP d'un espace de travail dans BlueXP"^]



==== Tracker disponible pour les opérations de surveillance et de suivi

Tracker, une nouvelle fonctionnalité de surveillance, est disponible dans BlueXP  Amazon FSX pour NetApp ONTAP. Vous pouvez utiliser Tracker pour surveiller et suivre la progression et l'état des informations d'identification, du stockage et des opérations de liaison, examiner les détails des tâches d'opération et des sous-tâches, diagnostiquer tout problème ou échec, modifier les paramètres pour les opérations ayant échoué et réessayer les opérations ayant échoué.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Découvrez comment surveiller et suivre les opérations FSX pour ONTAP dans BlueXP"^]



==== CloudShell disponible pour les charges de travail BlueXP

CloudShell est disponible lorsque vous travaillez avec des charges de travail BlueXP  au sein de la console BlueXP . CloudShell vous permet d'utiliser les informations d'identification AWS et ONTAP que vous avez fournies dans votre compte BlueXP  et d'exécuter les commandes CLI AWS ou les commandes de l'interface de ligne de commande ONTAP dans un environnement de type shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"^]



== Le stockage Amazon S3



=== 5 mars 2023



==== Possibilité d'ajouter de nouveaux compartiments à partir de BlueXP

Vous avez depuis longtemps la possibilité d'afficher les compartiments Amazon S3 sur BlueXP Canvas. Vous pouvez désormais ajouter de nouveaux compartiments et modifier les propriétés des compartiments existants directement à partir de BlueXP . https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["Découvrez comment ajouter de nouveaux compartiments Amazon S3"].



== Stockage Azure Blob



=== 5 juin 2023



==== Possibilité d'ajouter de nouveaux comptes de stockage à partir de BlueXP

Vous avez pu afficher Azure Blob Storage sur BlueXP Canvas pendant un certain temps. Vous pouvez désormais ajouter de nouveaux comptes de stockage et modifier les propriétés des comptes de stockage existants directement à partir de BlueXP . https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Découvrez comment ajouter de nouveaux comptes de stockage Azure Blob"].



== Azure NetApp Files



=== 13 janvier 2025



==== Fonctionnalités réseau désormais prises en charge dans BlueXP

Lors de la configuration d'un volume dans Azure NetApp Files à partir de BlueXP , vous pouvez maintenant indiquer les fonctionnalités réseau. Cette configuration s'aligne sur la fonctionnalité disponible dans Azure NetApp Files natif.



=== 12 juin 2024



==== Nouvelle autorisation requise

L'autorisation suivante est désormais requise pour gérer les volumes Azure NetApp Files à partir de BlueXP :

Microsoft.Network/virtualNetworks/subnets/read

Cette autorisation est requise pour lire un sous-réseau de réseau virtuel.

Si vous gérez actuellement Azure NetApp Files à partir de BlueXP, vous devez ajouter cette autorisation au rôle personnalisé associé à l'application Microsoft Entra que vous avez créée précédemment.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Découvrez comment configurer une application Microsoft Entra et afficher les autorisations de rôle personnalisées"].



=== 22 avril 2024



==== Les modèles de volume ne sont plus pris en charge

Vous ne pouvez plus créer de volume à partir d'un modèle. Cette action a été associée au service de correction BlueXP, qui n'est plus disponible.



== Sauvegarde et restauration



=== 16 avril 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



==== Tableau de bord de volume amélioré (aperçu)

Le tableau de bord de volume se charge désormais en moins de 10 secondes, offrant ainsi une interface beaucoup plus rapide et efficace. Cette version préliminaire est disponible pour certains clients, leur offrant un aperçu de ces améliorations.



==== Améliorations de l'interface utilisateur

Cette version améliore votre expérience en simplifiant l'interface :

* La suppression de la colonne Aggregate des tables volumes, ainsi que des colonnes Snapshot Policy, Backup Policy et Replication Policy de la table Volume du tableau de bord V2, entraîne une mise en page plus rationalisée.
* L'exclusion des environnements de travail non activés dans la liste déroulante rend l'interface moins encombrée, la navigation plus efficace et le chargement plus rapide.
* Lorsque le tri dans la colonne balises est désactivé, vous pouvez toujours afficher les balises, en vous assurant que les informations importantes restent facilement accessibles.
* Le retrait des étiquettes sur les icônes de protection contribue à un aspect plus propre et réduit le temps de chargement.
* Pendant le processus d'activation de l'environnement de travail, une boîte de dialogue affiche une icône de chargement pour fournir des informations jusqu'à ce que le processus de découverte soit terminé, ce qui améliore la transparence et la confiance dans les opérations du système.




==== Prise en charge d'un magasin d'objets Wasabi tiers (aperçu)

La sauvegarde et la restauration BlueXP  étendent désormais sa prise en charge aux magasins d'objets tiers, en mettant l'accent sur Wasabi. Cette nouvelle fonctionnalité de préversion vous permet d'exploiter un magasin d'objets compatible S3 pour vos besoins de sauvegarde et de restauration.



===== Mise en route de Wasabi

Pour commencer à utiliser cette fonctionnalité, vous devez activer un indicateur dans l'interface utilisateur de BlueXP . Vous pouvez ensuite saisir les informations de connexion de votre magasin d'objets tiers et l'intégrer à vos workflows de sauvegarde et de restauration.



===== Limites du mode d'aperçu

Lorsque cette fonction est en aperçu, tenez compte des limitations suivantes :

* Le modèle BYOB (Bring Your Own Bucket) n'est pas pris en charge.
* L'activation de DataLock dans une stratégie n'est pas prise en charge.
* L'activation du mode archivage dans une règle n'est pas prise en charge.
* Seuls les environnements ONTAP sur site sont pris en charge.
* MetroCluster n'est pas pris en charge.
* Les options d'activation du chiffrement au niveau du compartiment ne sont pas prises en charge.


Au cours de cette présentation, nous vous encourageons à explorer cette nouvelle fonctionnalité et à nous faire part de vos commentaires sur l'intégration à des magasins d'objets tiers avant le déploiement complet des fonctionnalités.



=== 17 mars 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



==== Exploration des snapshots SMB

Cette mise à jour de sauvegarde et de restauration BlueXP  a résolu un problème qui empêchait les clients de parcourir les snapshots locaux dans un environnement SMB.



==== Mise à jour de l'environnement AWS GovCloud

Cette mise à jour de sauvegarde et de restauration BlueXP  a résolu un problème qui empêchait l'interface utilisateur de se connecter à un environnement AWS GovCloud en raison d'erreurs de certificat TLS. Le problème a été résolu en utilisant le nom d'hôte du connecteur BlueXP  au lieu de l'adresse IP.



==== Limites de conservation des règles de sauvegarde

Jusqu'à présent, l'interface de sauvegarde et de restauration de BlueXP  limitait les sauvegardes à 999 copies, tandis que l'interface de ligne de commandes permettait d'en effectuer davantage. Vous pouvez désormais relier jusqu'à 4,000 volumes à une règle de sauvegarde et inclure 1,018 volumes non rattachés à une règle de sauvegarde. Cette mise à jour inclut des validations supplémentaires qui empêchent de dépasser ces limites.



==== Resynchronisation du cloud SnapMirror

Cette mise à jour garantit que la resynchronisation du cloud SnapMirror ne peut pas être démarrée à partir de la sauvegarde et de la restauration BlueXP  pour les versions ONTAP non prises en charge après la suppression d'une relation SnapMirror.



=== 21 février 2025

Cette version de sauvegarde et de restauration BlueXP  comprend les mises à jour suivantes.



==== Indexation haute performance

La sauvegarde et la restauration BlueXP  proposent une fonction d'indexation mise à jour qui optimise l'indexation des données dans l'environnement de travail source. La nouvelle fonction d'indexation inclut des mises à jour de l'interface utilisateur, des performances améliorées de la méthode de recherche et de restauration des données, des mises à niveau vers des fonctionnalités de recherche globale et une meilleure évolutivité.

Voici une description des améliorations :

* *Consolidation des dossiers* : la version mise à jour regroupe les dossiers en utilisant des noms qui incluent des identificateurs spécifiques, rendant le processus d'indexation plus fluide.
* *Compactage du fichier parquet* : la version mise à jour réduit le nombre de fichiers utilisés pour indexer chaque volume, ce qui simplifie le processus et élimine le besoin d'une base de données supplémentaire.
* *Scale-out avec plus de sessions*: La nouvelle version ajoute plus de sessions pour gérer les tâches d'indexation, ce qui accélère le processus.
* *Prise en charge de plusieurs conteneurs d'index* : la nouvelle version utilise plusieurs conteneurs pour mieux gérer et distribuer les tâches d'indexation.
* *Flux de travail d'index partagé* : la nouvelle version divise le processus d'indexation en deux parties, améliorant ainsi l'efficacité.
* *Concurrence améliorée* : la nouvelle version permet de supprimer ou de déplacer des répertoires en même temps, accélérant ainsi le processus d'indexation.


.Qui bénéficie de cette fonctionnalité ?
La nouvelle fonction d'indexation est disponible pour tous les nouveaux clients.

.Comment activer l'indexation ?
Avant de pouvoir utiliser la méthode Search & Restore de restauration des données, vous devez activer l'« indexation » sur chaque environnement de travail source à partir duquel vous prévoyez de restaurer des volumes ou des fichiers. Cela permet au catalogue indexé de suivre chaque volume et chaque fichier de sauvegarde, ce qui accélère et optimise vos recherches.

Activez l'indexation sur l'environnement de travail source en sélectionnant l'option « Activer l'indexation » lorsque vous effectuez une recherche et une restauration.

Pour plus d'informations, reportez-vous à la documentation https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Comment restaurer des données ONTAP à l'aide de la fonction recherche et ampli ; Restaurer"].

.Échelle prise en charge
La nouvelle fonction d'indexation prend en charge les éléments suivants :

* Recherche globale efficace en moins de 3 minutes
* Jusqu'à 5 milliards de fichiers
* Jusqu'à 5000 volumes par cluster
* Jusqu'à 100 000 snapshots par volume
* La durée maximale pour l'indexation de la ligne de base est inférieure à 7 jours. La durée réelle varie en fonction de votre environnement.




==== Amélioration des performances de recherche globale

Cette version comprend également des améliorations des performances de recherche globale. Vous verrez maintenant des indicateurs de progression et des résultats de recherche plus détaillés, y compris le nombre de fichiers et le temps nécessaire à la recherche. Des conteneurs dédiés à la recherche et à l'indexation garantissent que les recherches globales sont effectuées en moins de cinq minutes.

Notez les considérations suivantes relatives à la recherche globale :

* Le nouvel index n'est pas effectué sur les instantanés libellés horaire.
* La nouvelle fonctionnalité d'indexation ne fonctionne que sur les copies Snapshot sur FlexVols et non sur les copies Snapshot sur FlexGroups.




== Classement



=== 14 avril 2025



==== Version 1.42

Cette version de classification BlueXP  inclut :

.Balayage en vrac pour les environnements de travail
La classification BlueXP  prend désormais en charge les opérations en bloc pour les environnements de travail. Vous pouvez choisir d'activer les analyses de mappage, d'activer les analyses de mappage et de classification, de désactiver les analyses ou de créer une configuration personnalisée sur l'ensemble des volumes de l'environnement de travail. Si vous effectuez une sélection pour un volume individuel, elle remplace la sélection en bloc. Pour effectuer une opération en bloc, accédez à la page **Configuration** et faites votre sélection.

.Télécharger le rapport d'enquête localement
La classification BlueXP  prend désormais en charge la possibilité de télécharger des rapports d'enquête de données localement pour les afficher dans le navigateur. Si vous choisissez l'option locale, l'investigation de données est uniquement disponible au format CSV et n'affiche que les 10,000 premières lignes de données.

Pour plus d'informations, voir link:task-investigate-data.html#create-the-data-investigation-report["Analysez les données stockées dans votre entreprise avec la classification BlueXP"].



=== 10 mars 2025



==== Version 1.41

Cette version de classification BlueXP  inclut des améliorations générales et des correctifs. Elle comprend également :

.État de l'acquisition
La classification BlueXP  suit désormais la progression en temps réel des acquisitions de cartographie et de classification _initial_ sur un volume. Des barres progressives séparées suivent les analyses de cartographie et de classification, présentant un pourcentage du total des fichiers analysés. Vous pouvez également passer le curseur de la souris sur une barre de progression pour afficher le nombre de fichiers analysés et le nombre total de fichiers. Le suivi de l'état de vos analyses permet d'obtenir des informations plus détaillées sur la progression de l'analyse, ce qui vous permet de mieux planifier vos analyses et de comprendre l'allocation des ressources.

Pour afficher l'état de vos acquisitions, accédez à **Configuration** dans la classification BlueXP , puis sélectionnez la **Configuration de l'environnement de travail**. La progression est affichée en ligne pour chaque volume.



=== 19 février 2025



==== Version 1.40

Cette version de classification BlueXP  inclut les mises à jour suivantes.

.Prise en charge de RHEL 9.5
Cette version prend en charge Red Hat Enterprise Linux v9.5 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 et 9.5.

.Prioriser les acquisitions de mappage uniquement
Lorsque vous effectuez des acquisitions de mappage uniquement, vous pouvez hiérarchiser les acquisitions les plus importantes. Cette fonction vous aide lorsque vous disposez de nombreux environnements de travail et que vous souhaitez vous assurer que les numérisations à haute priorité sont effectuées en premier.

Par défaut, les analyses sont mises en file d'attente en fonction de l'ordre dans lequel elles sont initiées. Avec la possibilité de hiérarchiser les numérisations, vous pouvez désormais déplacer les numérisations vers l'avant de la file d'attente. Plusieurs acquisitions peuvent être classées par ordre de priorité. La priorité est désignée dans un ordre de premier entrée et de premier sortie, ce qui signifie que la première analyse prioritaire se déplace vers l'avant de la file d'attente ; la deuxième analyse prioritaire devient la deuxième dans la file d'attente, etc.

La priorité est accordée une fois. Les nouvelles analyses automatiques des données de mappage sont effectuées dans l'ordre par défaut.

La priorisation est limitée à link:concept-cloud-compliance.html["analyses de mappage uniquement"]; elle n'est pas disponible pour les acquisitions de cartes et de classification.

Pour plus d'informations, voir link:task-managing-repo-scanning.html#prioritize-scans["Hiérarchiser les acquisitions"].

.Réessayez toutes les acquisitions
La classification BlueXP  prend désormais en charge la possibilité de recommencer par lots toutes les acquisitions ayant échoué.

Vous pouvez à présent relancer des acquisitions en mode batch avec la fonction **Réessayer tout**. Si les analyses de classification échouent en raison d'un problème temporaire, tel qu'une panne réseau, vous pouvez réessayer toutes les analyses en même temps à l'aide d'un seul bouton au lieu de les essayer à nouveau individuellement. Les acquisitions peuvent être relancées autant de fois que nécessaire.

Pour réessayer toutes les acquisitions :

. Dans le menu BlueXP  Classification, sélectionnez *Configuration*.
. Pour réessayer toutes les acquisitions ayant échoué, sélectionnez *Réessayer toutes les acquisitions*.


.Amélioration de la précision du modèle de catégorisation
La précision du modèle de machine learning du link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["catégories prédéfinies"] a augmenté de 11 %.



=== 22 janvier 2025



==== Version 1.39

Cette version de classification BlueXP  met à jour le processus d'exportation du rapport d'investigation de données. Cette mise à jour d'exportation est utile pour effectuer des analyses supplémentaires sur vos données, créer des visualisations supplémentaires sur les données ou partager les résultats de votre enquête de données avec d'autres personnes.

Auparavant, l'exportation du rapport d'investigation de données était limitée à 10,000 lignes. Avec cette version, la limite a été supprimée afin que vous puissiez exporter toutes vos données. Cette modification vous permet d'exporter davantage de données à partir de vos rapports d'investigation de données, vous offrant ainsi une plus grande flexibilité dans votre analyse de données.

Vous pouvez choisir l'environnement de travail, les volumes, le dossier de destination et le format JSON ou CSV. Le nom de fichier exporté inclut un horodatage qui vous aide à identifier le moment où les données ont été exportées.

Les environnements de travail pris en charge sont les suivants :

* Cloud Volumes ONTAP
* FSX pour ONTAP
* ONTAP
* Partager le groupe


L'exportation de données à partir du rapport d'investigation de données comporte les limites suivantes :

* Le nombre maximum d'enregistrements à télécharger est de 500 millions. Par type (fichiers, répertoires et tables)
* L'exportation d'un million de documents devrait prendre environ 35 minutes.


Pour plus de détails sur l'investigation des données et le rapport, voir https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Analysez les données stockées dans votre entreprise"].



=== 16 décembre 2024



==== Version 1.38

Cette version de classification BlueXP  inclut des améliorations générales et des correctifs.



== Cloud Volumes ONTAP



=== 14 avril 2025



==== La création des machines virtuelles de stockage est automatisée au moyen des API dans Google Cloud

Vous pouvez désormais utiliser les API BlueXP  pour automatiser la création des machines virtuelles de stockage dans Google Cloud. Vous utilisez cette fonctionnalité dans des configurations Cloud Volumes ONTAP haute disponibilité (HA), et vous pouvez désormais l'utiliser dans des déploiements à un seul nœud. Avec les API BlueXP , vous pouvez facilement créer, renommer et supprimer d'autres serveurs de stockage virtuels qui servent les données dans votre environnement Google Cloud, sans avoir à configurer manuellement les interfaces réseau, les LIF et les LIF de gestion requises. Cette automatisation simplifie le processus de gestion des machines virtuelles de stockage.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Gestion des machines virtuelles de stockage destinées à la transmission des données pour Cloud Volumes ONTAP dans Google Cloud"^]



=== 28 mars 2025



==== Déploiements en mode privé activés pour Cloud Volumes ONTAP 9.14.1

Vous pouvez désormais déployer Cloud Volumes ONTAP 9.14.1 en mode privé dans AWS, Azure et Google Cloud. Le mode privé est activé pour les déploiements à un seul nœud et haute disponibilité (HA) de Cloud Volumes ONTAP 9.14.1.

Pour plus d'informations sur les déploiements en mode privé, reportez-vous https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["Découvrez les modes de déploiement BlueXP"^]à la section .



=== 12 mars 2025



==== Prise en charge de nouvelles régions pour les déploiements de zones de disponibilité multiples dans Azure

Les régions suivantes prennent désormais en charge les déploiements HA de zones de disponibilité multiples dans Azure pour Cloud Volumes ONTAP 9.12.1 GA et versions ultérieures :

* Centre DES ÉTATS-UNIS
* US Gov Virginia (région du gouvernement des États-Unis - Virginie)


Pour obtenir la liste de toutes les régions, reportez-vous à la https://bluexp.netapp.com/cloud-volumes-global-regions["Carte des régions globales sous Azure"^].



== Cloud Volumes Service pour Google Cloud



=== 9 septembre 2020



==== Prise en charge de Cloud Volumes Service pour Google Cloud

Vous pouvez désormais gérer Cloud Volumes Service pour Google Cloud directement depuis BlueXP :

* Configurer et créer un environnement de travail
* Créez et gérez des volumes NFS v3 et NFS v4.1 pour les clients Linux et UNIX
* Créez et gérez des volumes SMB 3.x pour les clients Windows
* Créez, supprimez et restaurez des snapshots de volume




== Copie et synchronisation



=== 2 février 2025



==== Nouvelle prise en charge du système d'exploitation pour le courtier de données

Le courtier de données est désormais pris en charge sur les hôtes exécutant Red Hat Enterprise 9.4, Ubuntu 23.04 et Ubuntu 24.04.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Afficher la configuration requise pour l'hôte Linux"].



=== 27 octobre 2024



==== Correctifs de bogues

Nous avons mis à jour le service de copie et de synchronisation BlueXP ainsi que le courtier en données pour corriger quelques bugs. La nouvelle version du courtier de données est 1.0.56.



=== 16 septembre 2024



==== Correctifs de bogues

Nous avons mis à jour le service de copie et de synchronisation BlueXP ainsi que le courtier en données pour corriger quelques bugs. La nouvelle version du courtier de données est 1.0.55.



== Conseiller digital



=== 05 mars 2025



==== Upgrade Advisor

* Le DQP (Disk qualification Package) permet désormais de mettre à jour automatiquement les contrôleurs de disque et le firmware du périphérique de stockage en fonction de critères prédéfinis d'intégrité et de performance. Cela réduit les défaillances potentielles et améliore la fiabilité globale du système.
* La base de données Timezone (DB) a été introduite pour maintenir automatiquement l'alignement du système avec les dernières définitions de fuseau horaire. Ainsi, les opérations dépendant du temps se poursuivent sans problème, même en cas de modification des règles du fuseau horaire.




=== 12 décembre 2024



==== Upgrade Advisor

Vous pouvez désormais afficher le firmware de stockage, le firmware SP/BMC et le paquet anti-ransomware autonome (ARP) recommandés pour une mise à jour. link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["Découvrez comment consulter les recommandations de mise à jour du firmware"].



=== 04 décembre 2024



==== Widget AutoSupport

Le widget AutoSupport a été ajouté à l'écran principal du tableau de bord pour alerter les clients des problèmes liés à l'état de AutoSupport.



== Portefeuille digital



=== 10 mars 2025



==== Possibilité de supprimer des abonnements

Vous pouvez désormais supprimer les abonnements du portefeuille numérique si vous ne vous y êtes plus abonné.



==== Afficher la capacité consommée pour les abonnements Marketplace

Lorsque vous consultez les abonnements PAYGO, vous pouvez maintenant afficher la capacité consommée de l'abonnement.



=== 10 février 2025

Le portefeuille digital BlueXP  a été repensé pour être facile à utiliser. Il offre désormais une gestion supplémentaire des abonnements et des licences.



==== Nouveau tableau de bord vue d'ensemble

La page d'accueil du portefeuille digital comprend un tableau de bord mis à jour de vos licences NetApp et de vos abonnements Marketplace. Vous pouvez ainsi zoomer sur les services, les types de licences et les actions requises.



==== Configuration des abonnements aux informations d'identification

Le portefeuille numérique BlueXP  vous permet désormais de configurer vos abonnements aux informations d'identification du fournisseur. En général, vous le faites lors de votre premier abonnement à un abonnement Marketplace ou à un contrat annuel. Auparavant, la modification des informations d'identification de l'abonnement ne pouvait être effectuée que sur la page informations d'identification.



==== Association d'abonnements à des organisations

Vous pouvez maintenant mettre à jour l'organisation à laquelle un abonnement est associé directement depuis le portefeuille digital.



==== Gestion des licences Cloud volumes ONTAP

Vous gérez maintenant les licences Cloud Volumes ONTAP via la page d'accueil ou l'onglet *licences directes*. Utilisez l'onglet *abonnements Marketplace* pour afficher les informations relatives à votre abonnement.



=== 5 mars 2024



==== Reprise d'activité BlueXP

Le portefeuille digital BlueXP vous permet désormais de gérer les licences pour la reprise d'activité BlueXP. Vous pouvez ajouter des licences, mettre à jour des licences et afficher des détails sur la capacité sous licence.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Découvrez comment gérer les licences des services de données BlueXP"]



=== 30 juillet 2023



==== Améliorations apportées aux rapports d'utilisation

Plusieurs améliorations apportées aux rapports d'utilisation de Cloud Volumes ONTAP sont désormais disponibles :

* L'unité TIB est désormais incluse dans le nom des colonnes.
* Un nouveau champ _node(s)_ pour les numéros de série est maintenant inclus.
* Une nouvelle colonne _Workload Type_ est désormais incluse dans le rapport d'utilisation des machines virtuelles de stockage.
* Les noms des environnements de travail sont désormais inclus dans les rapports Storage VM et Volume usage.
* Le type de volume _file_ est maintenant nommé _Primary (Read/Write)_.
* Le type de volume _secondary_ est maintenant appelé _Secondary (DP)_.


Pour plus d'informations sur les rapports d'utilisation, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Télécharger les rapports d'utilisation"].



== Reprise après incident



=== 16 avril 2025

Version 4.3



==== Découverte planifiée pour les VM

La reprise sur incident BlueXP  effectue une détection toutes les 24 heures. Avec cette version, vous pouvez désormais personnaliser le calendrier de découverte pour répondre à vos besoins et réduire l'impact sur les performances lorsque vous en avez besoin. Par exemple, si vous disposez d'un grand nombre de machines virtuelles, vous pouvez définir la planification de la découverte pour qu'elle s'exécute toutes les 48 heures. Si vous disposez d'un petit nombre de machines virtuelles, vous pouvez définir la planification de découverte pour qu'elle s'exécute toutes les 12 heures.

Si vous ne souhaitez pas que wan planifie la découverte, vous pouvez désactiver l'option de découverte planifiée et actualiser la découverte manuellement à tout moment.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Ajoutez des sites de serveur vCenter"] .



==== Prise en charge des datastores de groupes de ressources

Auparavant, vous ne pouviez créer des groupes de ressources que par des machines virtuelles. Avec cette version, vous pouvez créer un groupe de ressources par datastores. Lorsque vous créez un plan de réplication et un groupe de ressources pour ce plan, toutes les machines virtuelles d'un datastore sont répertoriées. Cette option est utile si vous disposez d'un grand nombre de machines virtuelles et que vous souhaitez les regrouper par datastore.

Vous pouvez créer un groupe de ressources avec un datastore de l'une des manières suivantes :

* Lorsque vous ajoutez un groupe de ressources à l'aide de datastores, vous pouvez voir la liste des datastores. Vous pouvez sélectionner un ou plusieurs datastores pour créer un groupe de ressources.
* Lorsque vous créez un plan de réplication et un groupe de ressources dans le plan, vous pouvez voir les machines virtuelles dans les datastores.


Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



==== Notifications d'expiration de licence ou d'essai gratuit

Cette version fournit des notifications indiquant que l'essai gratuit expirera dans 60 jours pour vous assurer que vous avez le temps d'obtenir une licence. Cette version fournit également des notifications le jour de l'expiration de la licence.



==== Notification des mises à jour de service

Avec cette version, une bannière s'affiche en haut pour indiquer que les services sont en cours de mise à niveau et que le service est placé en mode de maintenance. La bannière s'affiche lorsque le service est mis à niveau et disparaît lorsque la mise à niveau est terminée. Bien que vous puissiez continuer à travailler dans l'interface utilisateur pendant la mise à niveau, vous ne pouvez pas soumettre de nouveaux travaux. Les tâches planifiées s'exécuteront une fois la mise à jour terminée et le service retournera en mode de production.



=== 19 février 2025

Version 4.2



==== Prise en charge de ASA r2 pour les machines virtuelles et les datastores sur stockage VMFS

Cette version de BlueXP  Disaster Recovery prend en charge ASA r2 pour les machines virtuelles et les datastores sur le stockage VMFS. Sur un système ASA r2, le logiciel ONTAP prend en charge les fonctionnalités SAN essentielles, tout en supprimant les fonctionnalités non prises en charge dans les environnements SAN.

Cette version prend en charge les fonctionnalités suivantes pour ASA r2 :

* Provisionnement de groupes de cohérence pour le stockage primaire (groupe de cohérence plat uniquement, c'est-à-dire un seul niveau sans structure hiérarchique)
* Opérations de sauvegarde (groupe de cohérence) incluant l'automatisation SnapMirror


La prise en charge de ASA r2 dans la reprise sur incident BlueXP  utilise ONTAP 9.16.1.

Les datastores peuvent être montés sur un volume ONTAP ou une unité de stockage ASA r2, mais un groupe de ressources dans BlueXP  Disaster Recovery ne peut pas inclure à la fois un datastore depuis ONTAP et un datastore depuis ASA r2. Vous pouvez sélectionner un datastore à partir de ONTAP ou un datastore à partir de ASA r2 dans un groupe de ressources.



=== 30 octobre 2024



==== Création de rapports

Vous pouvez désormais générer et télécharger des rapports pour vous aider à analyser votre environnement. Des rapports prédéfinis résument les basculements et les basculements, affichent les détails de réplication sur tous les sites et affichent les détails des tâches des sept derniers jours.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Créez des rapports de reprise d'activité"].



==== essai gratuit de 30 jours

Vous pouvez désormais vous inscrire pour bénéficier d'un essai gratuit de 30 jours de reprise d'activité BlueXP . Auparavant, les essais gratuits étaient de 90 jours.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configuration des licences"].



==== Désactivez et activez les plans de réplication

Une version précédente incluait des mises à jour de la structure de planification des tests de basculement, qui devait prendre en charge les planifications quotidiennes et hebdomadaires. Cette mise à jour exige que vous désactiviez et réactiviez tous les plans de réplication existants afin de pouvoir utiliser les nouveaux programmes de tests de basculement quotidiens et hebdomadaires. Il s'agit d'une exigence ponctuelle.

Voici comment :

. Dans le menu supérieur, sélectionnez *plans de réplication*.
. Sélectionnez un plan et sélectionnez l'icône actions pour afficher le menu déroulant.
. Sélectionnez *Désactiver*.
. Après quelques minutes, sélectionnez *Activer*.




==== Mappage de dossiers

Lorsque vous créez un plan de réplication et que vous mappez des ressources de calcul, vous pouvez désormais mapper des dossiers de sorte que les machines virtuelles soient restaurées dans un dossier que vous spécifiez pour le centre de données, le cluster et l'hôte.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



==== Détails sur les machines virtuelles disponibles pour le basculement, la restauration et le basculement de test

Lorsqu'une panne se produit et que vous démarrez un basculement, effectuez un retour arrière ou testez le basculement, vous pouvez désormais afficher les détails des machines virtuelles et identifier celles qui n'ont pas redémarré.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Basculement des applications vers un site distant"].



==== Délai de démarrage de la machine virtuelle avec séquence de démarrage ordonnée

Lorsque vous créez un plan de réplication, vous pouvez maintenant définir un délai de démarrage pour chaque machine virtuelle du plan. Cela vous permet de définir une séquence pour que les machines virtuelles commencent à s'assurer que toutes vos machines virtuelles prioritaires sont en cours d'exécution avant que les machines virtuelles prioritaires suivantes ne soient démarrées.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



==== Informations sur le système d'exploitation des machines virtuelles

Lorsque vous créez un plan de réplication, vous pouvez maintenant voir le système d'exploitation pour chaque machine virtuelle du plan. Ceci est utile pour décider comment regrouper des machines virtuelles dans un groupe de ressources.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



==== Alias de nom de VM

Lorsque vous créez un plan de réplication, vous pouvez à présent ajouter un préfixe et un suffixe aux noms des machines virtuelles sur le SIT de reprise après incident. Cela vous permet d'utiliser un nom plus descriptif pour les VM du plan.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"] .



==== Nettoyez les anciens snapshots

Vous pouvez supprimer tous les snapshots qui ne sont plus nécessaires au-delà du nombre de conservation spécifié. Les snapshots peuvent s'accumuler au fil du temps lorsque vous réduisez le nombre de conservation des snapshots et vous pouvez désormais les supprimer pour libérer de l'espace. Vous pouvez le faire à tout moment à la demande ou lorsque vous supprimez un plan de réplication.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérez les sites, les groupes de ressources, les plans de réplication, les datastores et les informations sur les machines virtuelles"] .



==== Réconcilier les instantanés

Vous pouvez désormais réconcilier les instantanés qui sont désynchronisés entre la source et la cible. Cela peut se produire si des snapshots sont supprimés sur une cible en dehors de la reprise sur incident BlueXP . Le service supprime automatiquement le snapshot sur la source toutes les 24 heures. Cependant, vous pouvez effectuer cette opération à la demande. Cette fonction vous permet de vous assurer que les snapshots sont cohérents sur tous les sites.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gérer les plans de réplication"] .



== Systèmes E-Series



=== 18 septembre 2022



==== Prise en charge des baies E-Series

Vous pouvez désormais découvrir vos systèmes E-Series directement à partir de BlueXP. La découverte des systèmes E-Series vous offre une vue complète des données dans l'ensemble de votre multicloud hybride.



== Efficacité économique



=== 15 mai 2024



==== Fonctionnalités désactivées

Certaines fonctionnalités d'efficacité économique de BlueXP  ont été temporairement désactivées :

* Mise à jour technologique
* Ajoutez de la capacité




=== 14 mars 2024



==== Options de mise à jour technologique

Si vous disposez de ressources existantes et souhaitez déterminer si une technologie doit être mise à jour, vous pouvez utiliser les options de mise à jour technologique d'efficacité économique BlueXP. Vous pouvez soit examiner une courte évaluation de vos workloads actuels et obtenir des recommandations, soit envoyer des journaux AutoSupport à NetApp au cours des 90 derniers jours, le service peut maintenant fournir une simulation des workloads pour voir les performances de vos workloads sur du nouveau matériel.

Vous pouvez également ajouter une charge de travail et exclure des charges de travail existantes de la simulation.

Auparavant, vous pouviez uniquement évaluer vos ressources et déterminer si une mise à jour technologique est recommandée ?

La fonction fait désormais partie de l'option Tech Refresh dans le menu de navigation de gauche.

En savoir plus sur https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Évaluer une mise à jour technologique"] le .



=== 08 novembre 2023



==== Mise à jour technologique

Cette version de BlueXP Economic Efficiency comprend une nouvelle option qui permet d'évaluer vos ressources et d'identifier si une mise à jour technologique est recommandée. Le service inclut une nouvelle option de mise à jour technologique dans le menu de navigation de gauche, de nouvelles pages sur lesquelles vous pouvez évaluer vos charges de travail et ressources actuelles, ainsi qu'un rapport qui vous fournit des recommandations.



== La mise en cache en périphérie

Le service de mise en cache BlueXP  Edge a été supprimé le 7 août 2024.



== Google Cloud Storage



=== 10 juillet 2023



==== Possibilité d'ajouter de nouveaux compartiments et de gérer les compartiments existants à partir de BlueXP

Vous avez pu afficher les compartiments Google Cloud Storage sur le canevas BlueXP pendant un certain temps. Vous pouvez désormais ajouter de nouveaux compartiments et modifier les propriétés des compartiments existants directement à partir de BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["Découvrez comment ajouter de nouveaux compartiments de stockage Google Cloud"].



== Kubernetes

La prise en charge de la détection et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.



== Rapports de migration

Le service de rapports de migration BlueXP  a été supprimé le 7 août 2024.



== Clusters ONTAP sur site



=== 26 novembre 2024



==== Prise en charge des systèmes ASA r2 en mode privé

Vous pouvez désormais découvrir les systèmes NetApp ASA r2 lorsque vous utilisez BlueXP  en mode privé. Cette prise en charge est disponible à partir de la version 3.9.46 du mode privé de BlueXP .

* https://docs.netapp.com/us-en/asa-r2/index.html["En savoir plus sur les systèmes ASA r2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Découvrez les modes de déploiement BlueXP"^]




=== 7 octobre 2024



==== Prise en charge des systèmes ASA r2

Vous pouvez désormais découvrir les systèmes NetApp ASA r2 dans BlueXP  lorsque vous utilisez BlueXP  en mode standard ou en mode restreint. Une fois que vous avez découvert un système NetApp ASA r2 et ouvert votre environnement de travail, vous accédez directement à System Manager.

Aucune autre option de gestion n'est disponible avec les systèmes ASA r2. Vous ne pouvez pas utiliser la vue Standard et vous ne pouvez pas activer les services BlueXP.

La découverte des systèmes ASA r2 n'est pas prise en charge lorsque vous utilisez BlueXP  en mode privé.

* https://docs.netapp.com/us-en/asa-r2/index.html["En savoir plus sur les systèmes ASA r2"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Découvrez les modes de déploiement BlueXP"^]




=== 22 avril 2024



==== Les modèles de volume ne sont plus pris en charge

Vous ne pouvez plus créer de volume à partir d'un modèle. Cette action a été associée au service de correction BlueXP, qui n'est plus disponible.



== Résilience opérationnelle



=== 02 avril 2023



==== Service de résilience opérationnelle BlueXP

Grâce au nouveau service de résilience opérationnelle BlueXP et à ses suggestions automatisées de résolution des problèmes opérationnels IT, vous pouvez implémenter des solutions suggérées avant une panne ou une défaillance.

La résilience opérationnelle est un service qui vous aide à analyser les alertes et les événements afin de préserver l'intégrité, la disponibilité et les performances des services et des solutions.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["En savoir plus sur la résilience opérationnelle de BlueXP"].



== Protection par ransomware



=== 14 avril 2025



==== Rapports d'exercice de préparation

Avec cette version, vous pouvez consulter des rapports d'exploration de la préparation aux attaques par ransomware. Une exploration de la préparation vous permet de simuler une attaque par ransomware sur un workload échantillon nouvellement créé. Ensuite, étudiez l'attaque simulée et restaurez la charge de travail de l'échantillon. Cette fonctionnalité vous aide à être sûr d'être préparé en cas d'attaque par ransomware réelle en testant les processus de notification d'alerte, de réponse et de restauration.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Évaluez le niveau de préparation à une attaque par ransomware"] .



==== Nouveaux rôles et autorisations de contrôle d'accès basés sur des rôles

Vous pouviez auparavant attribuer des rôles et des autorisations à des utilisateurs en fonction de leurs responsabilités, ce qui vous aidera à gérer l'accès des utilisateurs à la protection contre les ransomwares de BlueXP . Avec cette version, il existe deux nouveaux rôles spécifiques à la protection contre les ransomwares BlueXP  avec des autorisations mises à jour. Les nouveaux rôles sont :

* Administrateur de la protection contre les ransomwares
* Visualiseur de protection contre les ransomware


Pour plus d'informations sur les autorisations, reportez-vous https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["La protection BlueXP  contre les ransomwares permet un accès basé sur des rôles aux fonctionnalités"] à la section .



==== Améliorations de paiement

Cette version comprend plusieurs améliorations du processus de paiement.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Configurez les options de licence et de paiement"] .



=== 10 mars 2025



==== Simulez une attaque et répondez

Avec cette version, simulez une attaque par ransomware pour tester votre réponse à une alerte. Cette fonctionnalité vous aide à être sûr d'être préparé en cas d'attaque par ransomware réelle en testant les processus de notification d'alerte, de réponse et de restauration.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Évaluez le niveau de préparation à une attaque par ransomware"] .



==== Améliorations du processus de découverte

Cette version inclut des améliorations aux processus de découverte sélective et de redécouverte :

* Avec cette version, vous pouvez découvrir les nouveaux workloads qui ont été ajoutés aux environnements de travail précédemment sélectionnés.
* Vous pouvez également sélectionner _New_ environnements de travail dans cette version. Cette fonctionnalité vous aide à protéger les nouvelles charges de travail ajoutées à votre environnement.
* Vous pouvez effectuer ces processus de découverte au cours du processus de découverte initial ou à l'aide de l'option Paramètres.


Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Découvrez les nouveaux workloads créés pour les environnements de travail précédemment sélectionnés"] et https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configurez les fonctions à l'aide de l'option Paramètres"].



==== Alertes générées lors de la détection d'un cryptage élevé

Avec cette version, vous pouvez afficher des alertes lorsque un chiffrement élevé est détecté sur vos charges de travail, même sans modifications importantes des extensions de fichiers. Cette fonctionnalité, qui utilise l'IA ONTAP Autonomous ransomware protection (ARP), vous aide à identifier les workloads qui sont exposés à des attaques de ransomware. Utilisez cette fonction et téléchargez la liste complète des fichiers impactés avec ou sans modifications d'extension.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Répondez à la détection d'une alerte par ransomware"] .



=== 16 décembre 2024



==== Détectez les comportements anormaux des utilisateurs avec Data Infrastructure Insights Storage Workload Security

Avec cette version, vous pouvez utiliser Data Infrastructure Insights Storage Workload Security pour détecter les comportements anormaux des utilisateurs dans vos workloads de stockage. Cette fonctionnalité vous aide à identifier les menaces de sécurité potentielles et à bloquer les utilisateurs potentiellement malveillants pour protéger vos données.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Répondez à la détection d'une alerte par ransomware"] .

Avant d'utiliser Data Infrastructure Insights Storage Workload Security pour détecter les comportements anormaux d'utilisateurs, vous devez configurer l'option en utilisant l'option BlueXP  ransomware protection *Settings*.

Reportez-vous à la https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configurez les paramètres de protection contre les ransomwares BlueXP"].



==== Sélectionnez les workloads à découvrir et à protéger

Avec cette version, vous pouvez maintenant effectuer les opérations suivantes :

* Dans chaque connecteur, sélectionnez les environnements de travail dans lesquels vous souhaitez découvrir les workloads. Vous pouvez bénéficier de cette fonctionnalité si vous souhaitez protéger des charges de travail spécifiques dans votre environnement et non d'autres.
* Lors de la détection des workloads, vous pouvez activer la détection automatique des workloads par connecteur. Cette fonction vous permet de sélectionner les charges de travail à protéger.
* Découvrez les nouveaux workloads créés pour les environnements de travail précédemment sélectionnés.


Reportez-vous à la https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Découvrir les workloads"].



== Résolution

Le service de correction BlueXP a été supprimé le 22 avril 2024.



== La réplication



=== 18 septembre 2022



==== FSX pour ONTAP vers Cloud Volumes ONTAP

Vous pouvez désormais répliquer des données d'un système de fichiers Amazon FSX pour ONTAP vers Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Découvrez comment configurer la réplication des données"].



=== 31 juillet 2022



==== FSX pour ONTAP en tant que source de données

Vous pouvez désormais répliquer des données d'un système de fichiers Amazon FSX pour ONTAP vers les destinations suivantes :

* Amazon FSX pour ONTAP
* Cluster ONTAP sur site


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Découvrez comment configurer la réplication des données"].



=== 2 septembre 2021



==== Prise en charge d'Amazon FSX pour ONTAP

Vous pouvez désormais répliquer des données à partir d'un système Cloud Volumes ONTAP ou d'un cluster ONTAP sur site vers un système de fichiers Amazon FSX pour ONTAP.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Découvrez comment configurer la réplication des données"].



== Mises à jour de logiciels



=== 02 avril 2025



==== Risques atténués

Dans la section récapitulative des mises à jour logicielles BlueXP , vous pouvez maintenant afficher le nombre total de risques pouvant être atténués par la mise à jour du système d'exploitation. Cela permet aux utilisateurs d'évaluer les améliorations de sécurité et de stabilité de leur base d'installation.



=== 07 août 2024



==== Mise à jour ONTAP

Le service de mises à jour logicielles BlueXP  offre aux utilisateurs une expérience de mise à jour fluide en limitant les risques et en leur permettant d'exploiter pleinement les fonctionnalités ONTAP.

En savoir plus sur link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Mises à jour du logiciel BlueXP"].



== StorageGRID



=== 7 août 2024



==== Nouvelle vue avancée

À partir de StorageGRID 11.8, vous pouvez utiliser l'interface familière du Gestionnaire de grille pour gérer votre système StorageGRID à partir de BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Découvrez comment gérer StorageGRID à l'aide de la vue avancée"].



==== Possibilité d'examiner et d'approuver le certificat d'interface de gestion StorageGRID

Vous avez désormais la possibilité d'examiner et d'approuver un certificat d'interface de gestion StorageGRID lors de la découverte du système StorageGRID à partir de BlueXP . Vous pouvez également vérifier et approuver le dernier certificat d'interface de gestion StorageGRID sur une grille découverte.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Découvrez comment vérifier et approuver le certificat du serveur lors de la découverte du système."]



=== 18 septembre 2022



==== Prise en charge de StorageGRID

Vous pouvez désormais découvrir vos systèmes StorageGRID directement depuis BlueXP. La découverte de StorageGRID vous offre une vue complète sur les données dans l'ensemble de votre environnement multicloud hybride.



== Tiering



=== 9 août 2023



==== Utilisez un préfixe personnalisé pour le nom du compartiment

Auparavant, vous aviez besoin d'utiliser le préfixe par défaut « fabric-pool » lors de la définition du nom du compartiment, par exemple, _fabric-pool-bucket1_. Vous pouvez désormais utiliser un préfixe personnalisé pour nommer votre compartiment. Cette fonctionnalité n'est disponible que lors du Tiering des données vers Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["En savoir plus >>"].



==== Recherchez un cluster sur tous les connecteurs BlueXP

Si vous utilisez plusieurs connecteurs pour gérer tous les systèmes de stockage de votre environnement, certains clusters sur lesquels vous souhaitez implémenter la hiérarchisation peuvent se trouver dans différents connecteurs. Si vous n'êtes pas sûr de quel connecteur gère un certain cluster, vous pouvez rechercher sur tous les connecteurs à l'aide du Tiering BlueXP. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["En savoir plus >>"].



=== 4 juillet 2023



==== Réglez la bande passante pour transférer les données inactives

Lorsque vous activez le Tiering BlueXP, ONTAP peut utiliser une quantité illimitée de bande passante réseau pour transférer les données inactives des volumes du cluster vers le stockage objet. Si vous remarquez que le trafic de hiérarchisation affecte les charges de travail normales des utilisateurs, vous pouvez limiter la quantité de bande passante qui peut être utilisée pendant le transfert. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["En savoir plus >>"].



==== Événement de hiérarchisation affiché dans le Centre de notification

La fonctionnalité de Tiering « transférer des données supplémentaires d'une <name> de cluster vers un stockage objet pour améliorer votre efficacité du stockage » s'affiche désormais sous forme de notification lorsqu'un cluster effectue le Tiering de moins de 20 % de ses données inactives, y compris les clusters qui ne hiérarchise aucune donnée.

Cette notification est une « recommandation » pour vous aider à rendre vos systèmes plus efficaces et à réduire vos coûts de stockage. Il fournit un lien vers le https://bluexp.netapp.com/cloud-tiering-service-tco["Calculateur de coût total de possession et d'économies du Tiering BlueXP"^] pour vous aider à calculer vos économies.



=== 3 avril 2023



==== L'onglet licences a été supprimé

L'onglet Licensing a été supprimé de l'interface de Tiering BlueXP. Toutes les licences pour les abonnements PAYGO sont maintenant accessibles depuis le tableau de bord du Tiering BlueXP sur site. Il existe également un lien vers le portefeuille digital BlueXP depuis cette page pour afficher et gérer n'importe quel modèle de Tiering BlueXP BYOL (Bring Your Own License).



==== Les onglets de hiérarchisation ont été renommés et mis à jour

L'onglet « clusters » a été renommé « clusters » et l'onglet « Présentation sur site » a été renommé « Tableau de bord sur site ». Ces pages ont ajouté des informations qui vous aideront à déterminer si vous pouvez optimiser votre espace de stockage avec une configuration de hiérarchisation supplémentaire.



== Mise en cache du volume



=== 04 juin 2023



==== Mise en cache du volume

La mise en cache des volumes, fonctionnalité du logiciel ONTAP 9, est une fonctionnalité de mise en cache à distance qui simplifie la distribution des fichiers et réduit la latence des réseaux WAN en rapprochant vos utilisateurs et vos ressources de calcul, tout en réduisant les coûts de la bande passante WAN. La mise en cache du volume fournit un volume inscriptible persistant à un emplacement distant. Vous pouvez utiliser la mise en cache du volume BlueXP pour accélérer l'accès aux données ou pour décharger le trafic des volumes fortement sollicités. Les volumes de cache sont parfaitement adaptés aux charges de travail exigeant une capacité de lecture maximale, en particulier lorsque les clients doivent accéder aux mêmes données de manière répétée.

La mise en cache des volumes BlueXP vous offre des fonctionnalités de mise en cache pour le cloud, en particulier pour Amazon FSX pour NetApp ONTAP, Cloud Volumes ONTAP et pour vos environnements de travail sur site.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["En savoir plus sur la mise en cache de volumes BlueXP"].



== Usine de charge de travail



=== 30 mars 2025



==== CloudShell signale les réponses d'erreur générées par l'IA pour les commandes de l'interface de ligne de commande ONTAP

Lorsque vous utilisez CloudShell, chaque fois que vous exécutez une commande de l'interface de ligne de commande ONTAP et qu'une erreur se produit, vous pouvez obtenir des réponses d'erreur générées par l'IA incluant une description de l'échec, la cause de l'échec et une résolution détaillée.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== iam:mise à jour des autorisations SimulatePermissionPolicy

Vous pouvez désormais gérer les `iam:SimulatePrincipalPolicy` autorisations à partir de la console d'usine des charges de travail lorsque vous ajoutez des informations d'identification de compte AWS supplémentaires ou que vous ajoutez une nouvelle fonctionnalité de charge de travail telle que la charge de travail GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



=== 02 février 2025



==== CloudShell est disponible dans la console d'usine des charges de travail BlueXP

CloudShell est disponible à partir de n'importe quel emplacement de la console d'usine de la charge de travail BlueXP . CloudShell vous permet d'utiliser les informations d'identification AWS et ONTAP que vous avez fournies dans votre compte BlueXP  et d'exécuter les commandes de la CLI AWS ou les commandes de la CLI ONTAP dans un environnement de type shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== Mise à jour des autorisations pour les bases de données

L'autorisation suivante est maintenant disponible en _read_ mode pour les bases de données : `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



=== 22 janvier 2025



==== Autorisations d'usine des workloads BlueXP

Vous pouvez désormais afficher les autorisations utilisées par l'usine de workloads BlueXP  pour exécuter diverses opérations, depuis la découverte de vos environnements de stockage jusqu'au déploiement des ressources AWS, telles que les systèmes de fichiers dans le stockage ou les bases de connaissances pour les charges de travail GenAI. Vous pouvez afficher les règles et autorisations IAM pour les workloads Storage, Databases, VMware et GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Autorisations d'usine des workloads BlueXP"]
