= Connecteur 3.9.32
:allow-uri-read: 




=== Connecteur 3.9.32

* Vous pouvez désormais exporter les journaux d'audit à l'aide de l'API du service d'audit BlueXP.
+
Le service d'audit enregistre les informations relatives aux opérations effectuées par les services BlueXP. Cela inclut les espaces de travail, les connecteurs utilisés et d'autres données de télémétrie. Vous pouvez utiliser ces données pour déterminer quelles actions ont été effectuées, qui les a effectuées et quand elles ont eu lieu.

+
https://docs.netapp.com/us-en/bluexp-automation/audit/overview.html["En savoir plus sur l'utilisation de l'API de service d'audit"^]

+
Notez que ce lien est également accessible depuis l'interface utilisateur BlueXP sur la page Chronologie.

* Cette version de Connector inclut également des améliorations apportées à Cloud Volumes ONTAP et des clusters ONTAP sur site.
+
** https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#30-july-2023["Découvrez les améliorations apportées à Cloud Volumes ONTAP"^]
** https://docs.netapp.com/us-en/bluexp-ontap-onprem/whats-new.html#30-july-2023["Découvrez les améliorations apportées aux clusters sur site de ONTAP"^]



