= 3-2-1 création de la stratégie de sauvegarde lors de l'activation de la sauvegarde
:allow-uri-read: 




=== 3-2-1 création de la stratégie de sauvegarde lors de l'activation de la sauvegarde

Auparavant, des règles personnalisées devaient être créées avant de lancer une copie Snapshot, une réplication ou une sauvegarde. Vous pouvez désormais créer une règle pendant le processus d'activation de la sauvegarde à l'aide de l'interface de sauvegarde et de restauration de BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["En savoir plus sur les stratégies"].



=== Prise en charge de la restauration rapide à la demande des volumes ONTAP

La sauvegarde et la restauration BlueXP permettent désormais d'effectuer une « restauration rapide » d'un volume depuis le stockage cloud vers un système Cloud Volumes ONTAP. La restauration rapide est idéale pour les reprises après incident où vous devez fournir un accès à un volume dès que possible. Une restauration rapide restaure les métadonnées du fichier de sauvegarde sur un volume au lieu de restaurer l'intégralité du fichier de sauvegarde.

Le système de destination Cloud Volumes ONTAP doit exécuter ONTAP version 9.13.0 ou ultérieure. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["En savoir plus sur la restauration des données"].

Le moniteur des tâches de sauvegarde et de restauration BlueXP affiche également des informations sur la progression des tâches de restauration rapide.
