= Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)
:allow-uri-read: 




=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (cloud natif)

* Base de données Microsoft SQL Server
+
** Prend en charge la sauvegarde, la restauration et la restauration des bases de données Microsoft SQL Server résidant sur Amazon FSX pour NetApp ONTAP
** Toutes les opérations ne sont prises en charge que par le biais des API REST.


* Systèmes SAP HANA
+
** Lors de l'actualisation du système, le montage et le démontage automatiques des volumes sont effectués à l'aide de workflows au lieu de scripts
** Prend en charge l'ajout, la suppression, la modification, la suppression, la maintenance, et mise à niveau de l'hôte du plug-in à l'aide de l'interface utilisateur






=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les applications (hybride)

* Prend en charge le verrouillage des données et la protection contre les ransomware
* Prise en charge du déplacement des sauvegardes de StorageGRID vers le niveau d'archivage
* Prise en charge de la sauvegarde des données d'applications MongoDB, MySQL et PostgreSQL à partir des systèmes ONTAP sur site vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID. Vous pouvez restaurer les données si nécessaire.




=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les machines virtuelles

* Prise en charge du modèle de déploiement de proxy de connecteur

